matches:
  - trigger: ":uuid"
    replace: "{{command}}"
    propagate_case: true
    vars:
      - name: command
        type: shell
        params:
          cmd: "uuidgen"
          shell: wsl
  - trigger: ":nuuid"
    replace: "{{command}}"
    propagate_case: true
    vars:
      - name: command
        type: shell
        params:
          cmd: "uuidgen | sed 's/-//g'"
          shell: wsl
