# Alt codes

matches:
- trigger: ":alt1:"
  replace: "☺"
- trigger: ":alt2:"
  replace: "☻"
- trigger: ":alt3:"
  replace: "♥"
- trigger: ":alt4:"
  replace: "♦"
- trigger: ":alt5:"
  replace: "♣"
- trigger: ":alt6:"
  replace: "♠"
- trigger: ":alt7:"
  replace: "•"
- trigger: ":alt8:"
  replace: "◘"
- trigger: ":alt9:"
  replace: "○"
- trigger: ":alt10:"
  replace: "◙"
- trigger: ":alt11:"
  replace: "♂"
- trigger: ":alt12:"
  replace: "♀"
- trigger: ":alt13:"
  replace: "♪"
- trigger: ":alt14:"
  replace: "♫"
- trigger: ":alt15:"
  replace: "☼"
- trigger: ":alt16:"
  replace: "►"
- trigger: ":alt17:"
  replace: "◄"
- trigger: ":alt18:"
  replace: "↕"
- trigger: ":alt19:"
  replace: "‼"
- trigger: ":alt20:"
  replace: "¶"
- trigger: ":alt21:"
  replace: "§"
- trigger: ":alt22:"
  replace: "▬"
- trigger: ":alt23:"
  replace: "↨"
- trigger: ":alt24:"
  replace: "↑"
- trigger: ":alt25:"
  replace: "↓"
- trigger: ":alt26:"
  replace: "→"
- trigger: ":alt27:"
  replace: "←"
- trigger: ":alt28:"
  replace: "∟"
- trigger: ":alt29:"
  replace: "↔"
- trigger: ":alt30:"
  replace: "▲"
- trigger: ":alt31:"
  replace: "▼"
- trigger: ":alt32:"
  replace: "spc"
- trigger: ":alt33:"
  replace: "!"
- trigger: ":alt34:"
  replace: "\""
- trigger: ":alt35:"
  replace: "#"
- trigger: ":alt36:"
  replace: "$"
- trigger: ":alt37:"
  replace: "%"
- trigger: ":alt38:"
  replace: "&"
- trigger: ":alt39:"
  replace: "'"
- trigger: ":alt40:"
  replace: "("
- trigger: ":alt41:"
  replace: ")"
- trigger: ":alt42:"
  replace: "*"
- trigger: ":alt43:"
  replace: "+"
- trigger: ":alt44:"
  replace: ","
- trigger: ":alt45:"
  replace: "-"
- trigger: ":alt46:"
  replace: "."
- trigger: ":alt47:"
  replace: "/"
- trigger: ":alt48:"
  replace: "0"
- trigger: ":alt49:"
  replace: "1"
- trigger: ":alt50:"
  replace: "2"
- trigger: ":alt51:"
  replace: "3"
- trigger: ":alt52:"
  replace: "4"
- trigger: ":alt53:"
  replace: "5"
- trigger: ":alt54:"
  replace: "6"
- trigger: ":alt55:"
  replace: "7"
- trigger: ":alt56:"
  replace: "8"
- trigger: ":alt57:"
  replace: "9"
- trigger: ":alt58:"
  replace: ":"
- trigger: ":alt59:"
  replace: ";"
- trigger: ":alt60:"
  replace: "<"
- trigger: ":alt61:"
  replace: "="
- trigger: ":alt62:"
  replace: ">"
- trigger: ":alt63:"
  replace: "?"
- trigger: ":alt64:"
  replace: "@"
- trigger: ":alt65:"
  replace: "A"
- trigger: ":alt66:"
  replace: "B"
- trigger: ":alt67:"
  replace: "C"
- trigger: ":alt68:"
  replace: "D"
- trigger: ":alt69:"
  replace: "E"
- trigger: ":alt70:"
  replace: "F"
- trigger: ":alt71:"
  replace: "G"
- trigger: ":alt72:"
  replace: "H"
- trigger: ":alt73:"
  replace: "I"
- trigger: ":alt74:"
  replace: "J"
- trigger: ":alt75:"
  replace: "K"
- trigger: ":alt76:"
  replace: "L"
- trigger: ":alt77:"
  replace: "M"
- trigger: ":alt78:"
  replace: "N"
- trigger: ":alt79:"
  replace: "O"
- trigger: ":alt80:"
  replace: "P"
- trigger: ":alt81:"
  replace: "Q"
- trigger: ":alt82:"
  replace: "R"
- trigger: ":alt83:"
  replace: "S"
- trigger: ":alt84:"
  replace: "T"
- trigger: ":alt85:"
  replace: "U"
- trigger: ":alt86:"
  replace: "V"
- trigger: ":alt87:"
  replace: "W"
- trigger: ":alt88:"
  replace: "X"
- trigger: ":alt89:"
  replace: "Y"
- trigger: ":alt90:"
  replace: "Z"
- trigger: ":alt91:"
  replace: "["
- trigger: ":alt92:"
  replace: "\\"
- trigger: ":alt93:"
  replace: "]"
- trigger: ":alt94:"
  replace: "^"
- trigger: ":alt95:"
  replace: "_"
- trigger: ":alt96:"
  replace: "`"
- trigger: ":alt97:"
  replace: "a"
- trigger: ":alt98:"
  replace: "b"
- trigger: ":alt99:"
  replace: "c"
- trigger: ":alt100:"
  replace: "d"
- trigger: ":alt101:"
  replace: "e"
- trigger: ":alt102:"
  replace: "f"
- trigger: ":alt103:"
  replace: "g"
- trigger: ":alt104:"
  replace: "h"
- trigger: ":alt105:"
  replace: "i"
- trigger: ":alt106:"
  replace: "j"
- trigger: ":alt107:"
  replace: "k"
- trigger: ":alt108:"
  replace: "l"
- trigger: ":alt109:"
  replace: "m"
- trigger: ":alt110:"
  replace: "n"
- trigger: ":alt111:"
  replace: "o"
- trigger: ":alt112:"
  replace: "p"
- trigger: ":alt113:"
  replace: "q"
- trigger: ":alt114:"
  replace: "r"
- trigger: ":alt115:"
  replace: "s"
- trigger: ":alt116:"
  replace: "t"
- trigger: ":alt117:"
  replace: "u"
- trigger: ":alt118:"
  replace: "v"
- trigger: ":alt119:"
  replace: "w"
- trigger: ":alt120:"
  replace: "x"
- trigger: ":alt121:"
  replace: "y"
- trigger: ":alt122:"
  replace: "z"
- trigger: ":alt123:"
  replace: "{"
- trigger: ":alt124:"
  replace: "|"
- trigger: ":alt125:"
  replace: "}"
- trigger: ":alt126:"
  replace: "~"
- trigger: ":alt127:"
  replace: "⌂"
- trigger: ":alt128:"
  replace: "Ç"
- trigger: ":alt129:"
  replace: "ü"
- trigger: ":alt130:"
  replace: "é"
- trigger: ":alt131:"
  replace: "â"
- trigger: ":alt132:"
  replace: "ä"
- trigger: ":alt133:"
  replace: "à"
- trigger: ":alt134:"
  replace: "å"
- trigger: ":alt135:"
  replace: "ç"
- trigger: ":alt136:"
  replace: "ê"
- trigger: ":alt137:"
  replace: "ë"
- trigger: ":alt138:"
  replace: "è"
- trigger: ":alt139:"
  replace: "ï"
- trigger: ":alt140:"
  replace: "î"
- trigger: ":alt141:"
  replace: "ì"
- trigger: ":alt142:"
  replace: "Ä"
- trigger: ":alt143:"
  replace: "Å"
- trigger: ":alt144:"
  replace: "É"
- trigger: ":alt145:"
  replace: "æ"
- trigger: ":alt146:"
  replace: "Æ"
- trigger: ":alt147:"
  replace: "ô"
- trigger: ":alt148:"
  replace: "ö"
- trigger: ":alt149:"
  replace: "ò"
- trigger: ":alt150:"
  replace: "û"
- trigger: ":alt151:"
  replace: "ù"
- trigger: ":alt152:"
  replace: "ÿ"
- trigger: ":alt153:"
  replace: "Ö"
- trigger: ":alt154:"
  replace: "Ü"
- trigger: ":alt155:"
  replace: "¢"
- trigger: ":alt156:"
  replace: "£"
- trigger: ":alt157:"
  replace: "¥"
- trigger: ":alt158:"
  replace: "₧"
- trigger: ":alt159:"
  replace: "ƒ"
- trigger: ":alt160:"
  replace: "á"
- trigger: ":alt161:"
  replace: "í"
- trigger: ":alt162:"
  replace: "ó"
- trigger: ":alt163:"
  replace: "ú"
- trigger: ":alt164:"
  replace: "ñ"
- trigger: ":alt165:"
  replace: "Ñ"
- trigger: ":alt166:"
  replace: "ª"
- trigger: ":alt167:"
  replace: "º"
- trigger: ":alt168:"
  replace: "¿"
- trigger: ":alt169:"
  replace: "⌐"
- trigger: ":alt170:"
  replace: "¬"
- trigger: ":alt171:"
  replace: "½"
- trigger: ":alt172:"
  replace: "¼"
- trigger: ":alt173:"
  replace: "¡"
- trigger: ":alt174:"
  replace: "«"
- trigger: ":alt175:"
  replace: "»"
- trigger: ":alt176:"
  replace: "░"
- trigger: ":alt177:"
  replace: "▒"
- trigger: ":alt178:"
  replace: "▓"
- trigger: ":alt179:"
  replace: "│"
- trigger: ":alt180:"
  replace: "┤"
- trigger: ":alt181:"
  replace: "╡"
- trigger: ":alt182:"
  replace: "╢"
- trigger: ":alt183:"
  replace: "╖"
- trigger: ":alt184:"
  replace: "╕"
- trigger: ":alt185:"
  replace: "╣"
- trigger: ":alt186:"
  replace: "║"
- trigger: ":alt187:"
  replace: "╗"
- trigger: ":alt188:"
  replace: "╝"
- trigger: ":alt190:"
  replace: "╛"
- trigger: ":alt191:"
  replace: "┐"
- trigger: ":alt192:"
  replace: "└"
- trigger: ":alt193:"
  replace: "┴"
- trigger: ":alt194:"
  replace: "┬"
- trigger: ":alt195:"
  replace: "├"
- trigger: ":alt196:"
  replace: "─"
- trigger: ":alt197:"
  replace: "┼"
- trigger: ":alt198:"
  replace: "╞"
- trigger: ":alt199:"
  replace: "╟"
- trigger: ":alt200:"
  replace: "╚"
- trigger: ":alt201:"
  replace: "╔"
- trigger: ":alt202:"
  replace: "╩"
- trigger: ":alt203:"
  replace: "╦"
- trigger: ":alt204:"
  replace: "╠"
- trigger: ":alt205:"
  replace: "═"
- trigger: ":alt206:"
  replace: "╬"
- trigger: ":alt207:"
  replace: "╧"
- trigger: ":alt208:"
  replace: "╨"
- trigger: ":alt209:"
  replace: "╤"
- trigger: ":alt210:"
  replace: "╥"
- trigger: ":alt211:"
  replace: "╙"
- trigger: ":alt212:"
  replace: "╘"
- trigger: ":alt213:"
  replace: "╒"
- trigger: ":alt214:"
  replace: "╓"
- trigger: ":alt215:"
  replace: "╫"
- trigger: ":alt216:"
  replace: "╪"
- trigger: ":alt217:"
  replace: "┘"
- trigger: ":alt218:"
  replace: "┌"
- trigger: ":alt219:"
  replace: "█"
- trigger: ":alt220:"
  replace: "▄"
- trigger: ":alt221:"
  replace: "▌"
- trigger: ":alt222:"
  replace: "▐"
- trigger: ":alt223:"
  replace: "▀"
- trigger: ":alt224:"
  replace: "α"
- trigger: ":alt225:"
  replace: "ß"
- trigger: ":alt226:"
  replace: "Γ"
- trigger: ":alt227:"
  replace: "π"
- trigger: ":alt228:"
  replace: "Σ"
- trigger: ":alt229:"
  replace: "σ"
- trigger: ":alt230:"
  replace: "µ"
- trigger: ":alt231:"
  replace: "τ"
- trigger: ":alt232:"
  replace: "Φ"
- trigger: ":alt233:"
  replace: "Θ"
- trigger: ":alt234:"
  replace: "Ω"
- trigger: ":alt235:"
  replace: "δ"
- trigger: ":alt236:"
  replace: "∞"
- trigger: ":alt237:"
  replace: "φ"
- trigger: ":alt238:"
  replace: "ε"
- trigger: ":alt239:"
  replace: "∩"
- trigger: ":alt240:"
  replace: "≡"
- trigger: ":alt241:"
  replace: "±"
- trigger: ":alt242:"
  replace: "≥"
- trigger: ":alt243:"
  replace: "≤"
- trigger: ":alt244:"
  replace: "⌠"
- trigger: ":alt245:"
  replace: "⌡"
- trigger: ":alt246:"
  replace: "÷"
- trigger: ":alt247:"
  replace: "≈"
- trigger: ":alt248:"
  replace: "°"
- trigger: ":alt249:"
  replace: "∙"
- trigger: ":alt250:"
  replace: "·"
- trigger: ":alt251:"
  replace: "√"
- trigger: ":alt252:"
  replace: "ⁿ"
- trigger: ":alt253:"
  replace: "²"
- trigger: ":alt254:"
  replace: "■"
- trigger: ":alt255:"
  replace: "spc"
- trigger: ":alt0128:"
  replace: "€"
- trigger: ":alt0130:"
  replace: "‚"
- trigger: ":alt0131:"
  replace: "ƒ"
- trigger: ":alt0132:"
  replace: "„"
- trigger: ":alt0133:"
  replace: "…"
- trigger: ":alt0134:"
  replace: "†"
- trigger: ":alt0135:"
  replace: "‡"
- trigger: ":alt0136:"
  replace: "ˆ"
- trigger: ":alt0137:"
  replace: "‰"
- trigger: ":alt0138:"
  replace: "Š"
- trigger: ":alt0139:"
  replace: "‹"
- trigger: ":alt0140:"
  replace: "Œ"
- trigger: ":alt0142:"
  replace: "Ž"
- trigger: ":alt0145:"
  replace: "‘"
- trigger: ":alt0146:"
  replace: "’"
- trigger: ":alt0147:"
  replace: "“"
- trigger: ":alt0148:"
  replace: "”"
- trigger: ":alt0149:"
  replace: "•"
- trigger: ":alt0150:"
  replace: "–"
- trigger: ":alt0151:"
  replace: "—"
- trigger: ":alt0152:"
  replace: "˜"
- trigger: ":alt0153:"
  replace: "™"
- trigger: ":alt0154:"
  replace: "š"
- trigger: ":alt0155:"
  replace: "›"
- trigger: ":alt0156:"
  replace: "œ"
- trigger: ":alt0158:"
  replace: "ž"
- trigger: ":alt0159:"
  replace: "Ÿ"
- trigger: ":alt0160:"
  replace: "spc"
- trigger: ":alt0161:"
  replace: "¡"
- trigger: ":alt0162:"
  replace: "¢"
- trigger: ":alt0163:"
  replace: "£"
- trigger: ":alt0164:"
  replace: "¤"
- trigger: ":alt0165:"
  replace: "¥"
- trigger: ":alt0166:"
  replace: "¦"
- trigger: ":alt0167:"
  replace: "§"
- trigger: ":alt0168:"
  replace: "¨"
- trigger: ":alt0169:"
  replace: "©"
- trigger: ":alt0170:"
  replace: "ª"
- trigger: ":alt0171:"
  replace: "«"
- trigger: ":alt0172:"
  replace: "¬"
- trigger: ":alt0174:"
  replace: "®"
- trigger: ":alt0175:"
  replace: "¯"
- trigger: ":alt0176:"
  replace: "°"
- trigger: ":alt0177:"
  replace: "±"
- trigger: ":alt0178:"
  replace: "²"
- trigger: ":alt0179:"
  replace: "³"
- trigger: ":alt0180:"
  replace: "´"
- trigger: ":alt0181:"
  replace: "µ"
- trigger: ":alt0182:"
  replace: "¶"
- trigger: ":alt0183:"
  replace: "·"
- trigger: ":alt0184:"
  replace: "¸"
- trigger: ":alt0185:"
  replace: "¹"
- trigger: ":alt0186:"
  replace: "º"
- trigger: ":alt0187:"
  replace: "»"
- trigger: ":alt0188:"
  replace: "¼"
- trigger: ":alt0189:"
  replace: "½"
- trigger: ":alt0190:"
  replace: "¾"
- trigger: ":alt0191:"
  replace: "¿"
- trigger: ":alt0192:"
  replace: "À"
- trigger: ":alt0193:"
  replace: "Á"
- trigger: ":alt0194:"
  replace: "Â"
- trigger: ":alt0195:"
  replace: "Ã"
- trigger: ":alt0196:"
  replace: "Ä"
- trigger: ":alt0197:"
  replace: "Å"
- trigger: ":alt0198:"
  replace: "Æ"
- trigger: ":alt0199:"
  replace: "Ç"
- trigger: ":alt0200:"
  replace: "È"
- trigger: ":alt0201:"
  replace: "É"
- trigger: ":alt0202:"
  replace: "Ê"
- trigger: ":alt0203:"
  replace: "Ë"
- trigger: ":alt0204:"
  replace: "Ì"
- trigger: ":alt0205:"
  replace: "Í"
- trigger: ":alt0206:"
  replace: "Î"
- trigger: ":alt0207:"
  replace: "Ï"
- trigger: ":alt0208:"
  replace: "Ð"
- trigger: ":alt0209:"
  replace: "Ñ"
- trigger: ":alt0210:"
  replace: "Ò"
- trigger: ":alt0211:"
  replace: "Ó"
- trigger: ":alt0212:"
  replace: "Ô"
- trigger: ":alt0213:"
  replace: "Õ"
- trigger: ":alt0214:"
  replace: "Ö"
- trigger: ":alt0215:"
  replace: "×"
- trigger: ":alt0216:"
  replace: "Ø"
- trigger: ":alt0217:"
  replace: "Ù"
- trigger: ":alt0218:"
  replace: "Ú"
- trigger: ":alt0219:"
  replace: "Û"
- trigger: ":alt0220:"
  replace: "Ü"
- trigger: ":alt0221:"
  replace: "Ý"
- trigger: ":alt0222:"
  replace: "Þ"
- trigger: ":alt0223:"
  replace: "ß"
- trigger: ":alt0224:"
  replace: "à"
- trigger: ":alt0225:"
  replace: "á"
- trigger: ":alt0226:"
  replace: "â"
- trigger: ":alt0227:"
  replace: "ã"
- trigger: ":alt0228:"
  replace: "ä"
- trigger: ":alt0229:"
  replace: "å"
- trigger: ":alt0230:"
  replace: "æ"
- trigger: ":alt0231:"
  replace: "ç"
- trigger: ":alt0232:"
  replace: "è"
- trigger: ":alt0233:"
  replace: "é"
- trigger: ":alt0234:"
  replace: "ê"
- trigger: ":alt0235:"
  replace: "ë"
- trigger: ":alt0236:"
  replace: "ì"
- trigger: ":alt0237:"
  replace: "í"
- trigger: ":alt0238:"
  replace: "î"
- trigger: ":alt0239:"
  replace: "ï"
- trigger: ":alt0240:"
  replace: "ð"
- trigger: ":alt0241:"
  replace: "ñ"
- trigger: ":alt0242:"
  replace: "ò"
- trigger: ":alt0243:"
  replace: "ó"
- trigger: ":alt0244:"
  replace: "ô"
- trigger: ":alt0245:"
  replace: "õ"
- trigger: ":alt0246:"
  replace: "ö"
- trigger: ":alt0247:"
  replace: "÷"
- trigger: ":alt0248:"
  replace: "ø"
- trigger: ":alt0249:"
  replace: "ù"
- trigger: ":alt0250:"
  replace: "ú"
- trigger: ":alt0251:"
  replace: "û"
- trigger: ":alt0252:"
  replace: "ü"
- trigger: ":alt0253:"
  replace: "ý"
- trigger: ":alt0254:"
  replace: "þ"
- trigger: ":alt0255:"
  replace: "ÿ"
