# Math

matches:
  # Booleans
  - trigger: ":and"
    replace: "∧"
  - trigger: ":or"
    replace: "∨"
  - trigger: ":xor"
    replace: "⩛"
  # Propositions
  - trigger: ":not"
    replace: "¬"
  - trigger: ":impl"
    replace: "⇒"
  - trigger: ":equiv"
    replace: "⇔"
  # Sets
  - trigger: ":forall"
    replace: "∀"
  - trigger: ":exist"
    replace: "∃"
  - trigger: ":inset"
    replace: "∈"
  - trigger: ":notin"
    replace: "∉"
  - trigger: ":niset"
    replace: "∋"
  - trigger: ":notni"
    replace: "∌"
  - trigger: ":subset"
    replace: "⊂"
  - trigger: ":subseq"
    replace: "⊆"
  - trigger: ":supset"
    replace: "⊃"
  - trigger: ":supseq"
    replace: "⊇"
  - trigger: ":union"
    replace: "∪"
  - trigger: ":intersect"
    replace: "∩"
  # Proofs
  - trigger: ":therefore"
    replace: "∴"
  - trigger: ":because"
    replace: "∵"
  - trigger: ":qed"
    replace: "■"
  # Misc
  - trigger: ":cong"
    replace: "≅"
  - trigger: ":sqrt"
    replace: "√"
  - trigger: ":approx"
    replace: "≈"
  - trigger: ":sum"
    replace: "∑"
  - trigger: ":integral"
    replace: "∫"
  - trigger: ":dagger"
    replace: "†"
