matches:
  # æøå
  - trigger: ":ae"
    label: "æÆ"
    replace: "æ"
    propagate_case: true 
  - trigger: ":oe"
    label: "øØ"
    replace: "ø"
    propagate_case: true
  - trigger: ":aa"
    label: "åÅ"
    replace: "å"
    propagate_case: true

  # acute accents
  - trigger: ":e'"
    label: "éÉ (e acute)"
    replace: "é"
    propagate_case: true
  
  # grave accents
  - trigger: ":a`"
    label : "àÀ (a grave)"
    replace: "à"
    propagate_case: true
  - trigger: ":o`"
    label: "òÒ (o grave)"
    replace: "ò"
    propagate_case: true

  # Norwegian quote marks
  - trigger: ":`"
    label: "« (open quote)"
    replace: "«"
  - trigger: ":'"
    label: "» (close quote)"
    replace: "»"
