matches:
  - trigger: ';"'
    replace: "“$|$”"

  - trigger: ";'"
    replace: "‘$|$’"

  - trigger: "''"
    replace: "’"

  - trigger: ";;n"
    replace: "–"

  - trigger: ";;m"
    replace: "—"

  - trigger: '...'
    replace: '…'

  - trigger: ';<<'
    replace: '«'

  - trigger: ';>>'
    replace: '»'

  - trigger: ';<-'
    replace: '←'

  - trigger: ';->'
    replace: '→'

  - trigger: ';<='
    replace: '≤'

  - trigger: ';>='
    replace: '≥'

  - trigger: ';/='
    replace: '≠'

  - regex: '(?P<num1>\d+)/(?P<num2>\w+ )'
    replace: "{{num1}}⁄{{num2}}"
