
matches:
  # {{{ Double Stroke Letters
  # https;//www.webnots.com/alt-code-shortcuts-for-double-stroke-letters-and-numbers/
  - trigger: ';//A'
    replace: '𝔸'
  - trigger: ';//B'
    replace: '𝔹'
  - trigger: ';//C'
    replace: 'ℂ'
  - trigger: ';//D'
    replace: '𝔻'
  - trigger: ';//E'
    replace: '𝔼'
  - trigger: ';//F'
    replace: '𝔽'
  - trigger: ';//G'
    replace: '𝔾'
  - trigger: ';//H'
    replace: 'ℍ'
  - trigger: ';//I'
    replace: '𝕀'
  - trigger: ';//J'
    replace: '𝕁'
  - trigger: ';//K'
    replace: '𝕂'
  - trigger: ';//L'
    replace: '𝕃'
  - trigger: ';//M'
    replace: '𝕄'
  - trigger: ';//N'
    replace: 'ℕ'
  - trigger: ';//O'
    replace: '𝕆'
  - trigger: ';//P'
    replace: 'ℙ'
  - trigger: ';//Q'
    replace: 'ℚ'
  - trigger: ';//R'
    replace: 'ℝ'
  - trigger: ';//S'
    replace: '𝕊'
  - trigger: ';//T'
    replace: '𝕋'
  - trigger: ';//U'
    replace: '𝕌'
  - trigger: ';//V'
    replace: '𝕍'
  - trigger: ';//W'
    replace: '𝕎'
  - trigger: ';//X'
    replace: '𝕏'
  - trigger: ';//Y'
    replace: '𝕐'
  - trigger: ';//Z'
    replace: 'ℤ'
  - trigger: ';//a'
    replace: '𝕒'
  - trigger: ';//b'
    replace: '𝕓'
  - trigger: ';//c'
    replace: '𝕔'
  - trigger: ';//d'
    replace: '𝕕'
  - trigger: ';//e'
    replace: '𝕖'
  - trigger: ';//f'
    replace: '𝕗'
  - trigger: ';//g'
    replace: '𝕘'
  - trigger: ';//h'
    replace: '𝕙'
  - trigger: ';//i'
    replace: '𝕚'
  - trigger: ';//j'
    replace: '𝕛'
  - trigger: ';//k'
    replace: '𝕜'
  - trigger: ';//l'
    replace: '𝕝'
  - trigger: ';//m'
    replace: '𝕞'
  - trigger: ';//n'
    replace: '𝕟'
  - trigger: ';//o'
    replace: '𝕠'
  - trigger: ';//p'
    replace: '𝕡'
  - trigger: ';//q'
    replace: '𝕢'
  - trigger: ';//r'
    replace: '𝕣'
  - trigger: ';//s'
    replace: '𝕤'
  - trigger: ';//t'
    replace: '𝕥'
  - trigger: ';//u'
    replace: '𝕦'
  - trigger: ';//v'
    replace: '𝕧'
  - trigger: ';//w'
    replace: '𝕨'
  - trigger: ';//x'
    replace: '𝕩'
  - trigger: ';//y'
    replace: '𝕪'
  - trigger: ';//z'
    replace: '𝕫'
  # }}}
