matches:
  - trigger: ":shrug"
    replace: "¯\_(ツ)_/¯"
  - trigger: ":lenny"
    replace: "( ͡° ͜ʖ ͡°)"
  - trigger: ":fliptable"
    replace: "(╯°□°）╯︵ ┻━┻"
  - trigger: ":disapprove"
    replace: "ಠ_ಠ"
  - trigger: ":denko"
    replace: "(´・ω・｀)"
  - trigger: ":owo"
    replace: "ʘwʘ"
  - trigger: ":hello"
    replace: "( ･ω･)ﾉ"
  - trigger: ":cry"
    replace: "ಥ益ಥ"
  - trigger: ":mad"
    replace: "(๑•̀д•́๑)"
  - trigger: ":awk"
    replace: "( ་ ⍸ ་ )"
  - trigger: ":pika"
    replace: "(๑◕ܫ◕๑)"
  - trigger: ":donger"
    replace: "ヽ༼ຈل͜ຈ༽ﾉ"
  - trigger: ":sparkle"
    replace: "✧･ﾟ: *✧･ﾟ:* 　$|$　 *:･ﾟ✧*:･ﾟ✧"
