# Excel package

matches:
  - triggers: ["e.first", "e.firstname"]
    replace: '=LEFT(A2, SEARCH(" ", A2)-1)'

  - triggers: ["e.mid", "e.middlename"]
    replace: '=MID(A2, SEARCH(" ", A2)+1, SEARCH(" ", A2, SEARCH(" ", A2)+1) - SEARCH(" ", A2)-1)'

  - triggers: ["e.last", "e.lastname"]
    replace: '=RIGHT(A2, LEN(A2) - SEARCH(" ", A2, SEARCH(" ", A2, 1)+1))'
