matches:

  - trigger: ":angelo"
    replace: "🗿"

  - trigger: ":nice"
    replace: "https://imgur.com/yFsi2sj"
  
  - trigger: ":omg"
    replace: "https://imgur.com/OFEhWLt"
    
  - trigger: ":okmasta"
    replace: "https://imgur.com/uMt4FVE"
    
  - trigger: ":relo"
    replace: "https://imgur.com/92u2qsw"
    
  - trigger: ":iam"
    replace: "https://imgur.com/5TGCZO5"
    
  - trigger: ":yesomg"
    replace: "https://imgur.com/5hPKiEm"
  
  - trigger: ":no"
    replace: "https://imgur.com/5qV57FJ"

  - trigger: ":yes"
    replace: "https://imgur.com/SN9R0EG"