# German Accents

# Lowercase
matches:
  - trigger: "a\""
    replace: "ä"

  - trigger: "o\""
    replace: "ö"

  - trigger: "u\""
    replace: "ü"

  - trigger: "s\""
    replace: "ß"

# Uppercase

  - trigger: "A\""
    replace: "Ä"

  - trigger: "O\""
    replace: "Ö"

  - trigger: "U\""
    replace: "Ü"
