# Docker compose Package

matches:
  - trigger: ":dbuild"
    replace: "docker-compose build"
    
  - trigger: ":dup"
    replace: "docker-compose up"

  - trigger: ":dupd"
    replace: "docker-compose up -d"
    
  - trigger: ":ddown"
    replace: "docker-compose down"

  - trigger: ":dlogs"
    replace: "docker-compose logs"
    
  - trigger: ":dlogsf"
    replace: "docker-compose logs -f"

  - trigger: ":dexec"
    replace: "docker-compose exec"
    
  - trigger: ":drestart"
    replace: "docker-compose restart"
