filter_exec: obsidian

matches:
  - trigger: ">n"
    replace: "> [!note]+\n$|$"
  - trigger: ">a"
    replace: "> [!abstract]+\n$|$"
  - trigger: ">s"
    replace: "> [!summary]+\n$|$"
  - trigger: ">i"
    replace: "> [!info]+\n$|$"
  - trigger: ">t"
    replace: "> [!todo]+\n$|$"
  - trigger: ">p"
    replace: "> [!tip]+\n$|$"
  - trigger: ">k"
    replace: "> [!check]+\n$|$"
  - trigger: ">d"
    replace: "> [!done]+\n$|$"
  - trigger: ">?"
    replace: "> [!question]+\n$|$"
  - trigger: ">h"
    replace: "> [!help]+\n$|$"
  - trigger: ">w"
    replace: "> [!warning]+\n$|$"
  - trigger: ">x"
    replace: "> [!caution]+\n$|$"
  - trigger: ">f"
    replace: "> [!fail]+\n$|$"
  - trigger: ">m"
    replace: "> [!missing]+\n$|$"
  - trigger: ">b"
    replace: "> [!bug]+\n$|$"
  - trigger: ">e"
    replace: "> [!example]+\n$|$"
  - trigger: ">q"
    replace: "> [!quote]+\n$|$"
  - trigger: ">c"
    replace: "> [!cite]+\n$|$"

