matches:

  - trigger: ',"'
    replace: '“$|$”'

  - trigger: ",'"
    replace: '‘$|$’'

  - trigger: "''"
    replace: '’'

  - trigger: ',n'
    replace: '–'

  - trigger: ',m'
    replace: '—'

  - trigger: '...'
    replace: '…'

  - trigger: '<<'
    replace: '«'

  - trigger: '>>'
    replace: '»'

  - trigger: '<-'
    replace: '←'

  - trigger: '->'
    replace: '→'

  - trigger: '<='
    replace: '≤'

  - trigger: '>='
    replace: '≥'

  - trigger: '/='
    replace: '≠'

  - regex: '(?P<num1>\d+)/(?P<num2>\d+ )'
    replace: '{{num1}}⁄{{num2}}'

  - regex: '(?P<letter1>\w+)](?P<letter2>\w{2} )'
    replace: '{{letter1}}<sup>{{letter2}}</sup>'

  - regex: '(?P<letter1>\w+)}(?P<letter2>\w{2} )'
    replace: '{{letter1}}<sub>{{letter2}}</sub>'
