# wttr package

matches:
  - trigger: ":wttrin"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: 'curl https://wttr.in?format="%l:+%c+%t\n"'

  - trigger: ":moonphase"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: 'curl https://wttr.in?format="%m\n"'

  - trigger: ":wttrat/(?P<location>.*)/"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: 'curl https://wttr.in/{{location}}?format="%l:+%c+%t\n"'
