matches:
   - trigger: "a|!"
     replace: "ā"
   - trigger: "a|@"
     replace: "á"
   - trigger: "a|#"
     replace: "ǎ"
   - trigger: "a|$"
     replace: "à"
   - trigger: "e|!"
     replace: "ē"
   - trigger: "e|@"
     replace: "é"
   - trigger: "e|#"
     replace: "ě"
   - trigger: "e|$"
     replace: "è"
   - trigger: "i|!"
     replace: "ī"
   - trigger: "i|@"
     replace: "í"
   - trigger: "i|$"
     replace: "ì"
   - trigger: "i|#"
     replace: "ǐ"
   - trigger: "o|!"
     replace: "ō"
   - trigger: "o|@"
     replace: "ó"
   - trigger: "o|#"
     replace: "ǒ"
   - trigger: "o|$"
     replace: "ò"
   - trigger: "u|!"
     replace: "ū"
   - trigger: "u|@"
     replace: "ú"
   - trigger: "u|#"
     replace: "ǔ"
   - trigger: "u|$"
     replace: "ù"
   - trigger: "u:|!"
     replace: "ǖ"
   - trigger: "u:|@"
     replace: "ǘ"
   - trigger: "u:|#"
     replace: "ǚ"
   - trigger: "u:|$"
     replace: "ǜ"