matches:
  - { trigger: ":a11y", replace: "accessibility", propagate_case: true }
  - { trigger: ":a12n", replace: "authentication", propagate_case: true }
  - { trigger: ":a13n", replace: "authorization", propagate_case: true }
  - { trigger: ":c10t", replace: "concurrent", propagate_case: true }
  - { trigger: ":c10y", replace: "complexity", propagate_case: true }
  - { trigger: ":c11n", replace: "collaboration", propagate_case: true }
  - { trigger: ":c12n", replace: "configuration", propagate_case: true }
  - { trigger: ":c14n", replace: "canonicalization", propagate_case: true }
  - { trigger: ":d9t", replace: "development", propagate_case: true }
  - { trigger: ":d11n", replace: "documentation", propagate_case: true }
  - { trigger: ":e13t", replace: "entertainment", propagate_case: true }
  - { trigger: ":g11n", replace: "globalization", propagate_case: true }
  - { trigger: ":h10n", replace: "humanization", propagate_case: true }
  - { trigger: ":i14y", replace: "interoperability", propagate_case: true }
  - { trigger: ":i18n", replace: "internationalization", propagate_case: true }
  - { trigger: ":k8s", replace: "Kubernetes" }
  - { trigger: ":l10n", replace: "localization", propagate_case: true }
  - { trigger: ":m11t", replace: "microservices", propagate_case: true }
  - { trigger: ":m12n", replace: "modularization", propagate_case: true }
  - { trigger: ":n8n", replace: "notation", propagate_case: true }
  - { trigger: ":o11y", replace: "observability", propagate_case: true }
  - { trigger: ":o12n", replace: "optimization", propagate_case: true }
  - { trigger: ":p11y", replace: "portability", propagate_case: true }
  - { trigger: ":p13n", replace: "personalization", propagate_case: true }
  - { trigger: ":p8s", replace: "Prometheus" }
  - { trigger: ":r9y", replace: "reliability", propagate_case: true }
  - { trigger: ":r13t", replace: "responsibility", propagate_case: true }
  - { trigger: ":s5n", replace: "shorten", propagate_case: true }
  - { trigger: ":s10n", replace: "separation", propagate_case: true }
  - { trigger: ":s10y", replace: "scalability", propagate_case: true }
  - { trigger: ":s11y", replace: "sustainability", propagate_case: true }
  - { trigger: ":s12n", replace: "serialization", propagate_case: true }
  - { trigger: ":tr8n", replace: "translation", propagate_case: true }
  - { trigger: ":v11n", replace: "versification", propagate_case: true }
  - { trigger: ":v12n", replace: "virtualization", propagate_case: true }
