name: typofixer-fr
parent: default
matches:
- trigger: aggression
  replace: agression
  propagate_case: true
  word: true
- trigger: arreter
  replace: "arr\xEAter"
  propagate_case: true
  word: true
- trigger: ascenceur
  replace: ascenseur
  propagate_case: true
  word: true
- trigger: banlieu
  replace: banlieue
  propagate_case: true
  word: true
- trigger: banlieux
  replace: banlieues
  propagate_case: true
  word: true
- trigger: belle-soeur
  replace: "belle-s\u0153ur"
  propagate_case: true
  word: true
- trigger: bitter
  replace: biter
  propagate_case: true
  word: true
- trigger: bleux
  replace: bleus
  propagate_case: true
  word: true
- trigger: "bug\xE9taire"
  replace: "budg\xE9taire"
  propagate_case: true
  word: true
- trigger: "\xE7a et l\xE0"
  replace: "\xE7\xE0 et l\xE0"
  propagate_case: true
  word: true
- trigger: casress
  replace: caresse
  propagate_case: true
  word: true
- trigger: "cath\xE9chisme"
  replace: "cat\xE9chisme"
  propagate_case: true
  word: true
- trigger: cauchemard
  replace: cauchemar
  propagate_case: true
  word: true
- trigger: cauchemards
  replace: cauchemars
  propagate_case: true
  word: true
- trigger: "c\xE8ne"
  replace: "C\xE8ne"
  propagate_case: true
  word: true
- trigger: championat
  replace: championnat
  propagate_case: true
  word: true
- trigger: cidessus
  replace: ci-dessus
  propagate_case: true
  word: true
- trigger: collophane
  replace: colophane
  propagate_case: true
  word: true
- trigger: colocateur
  replace: colocataire
  propagate_case: true
  word: true
- trigger: colon
  replace: "c\xF4lon"
  propagate_case: true
  word: true
- trigger: colons
  replace: "c\xF4lons"
  propagate_case: true
  word: true
- trigger: "comp\xE9tivit\xE9"
  replace: "comp\xE9titivit\xE9"
  propagate_case: true
  word: true
- trigger: concience
  replace: conscience
  propagate_case: true
  word: true
- trigger: croissement
  replace: croisement
  propagate_case: true
  word: true
- trigger: "d\xE9barasser"
  replace: "d\xE9barrasser"
  propagate_case: true
  word: true
- trigger: "d\xE9fete"
  replace: "d\xE9faite"
  propagate_case: true
  word: true
- trigger: "d\xE9f\xE8te"
  replace: "d\xE9faite"
  propagate_case: true
  word: true
- trigger: derniere
  replace: "derni\xE8re"
  propagate_case: true
  word: true
- trigger: deshydrogenase
  replace: "d\xE9shydrog\xE9nase"
  propagate_case: true
  word: true
- trigger: ect.
  replace: etc.
  propagate_case: true
  word: true
- trigger: "ellesm\xEAmes"
  replace: "elles-m\xEAmes"
  propagate_case: true
  word: true
- trigger: entre-gens
  replace: entregent
  propagate_case: true
  word: true
- trigger: entrepreunariat
  replace: entrepreneuriat
  propagate_case: true
  word: true
- trigger: etaient
  replace: "\xE9taient"
  propagate_case: true
  word: true
- trigger: etait
  replace: "\xE9tait"
  propagate_case: true
  word: true
- trigger: etaits
  replace: "\xE9taits"
  propagate_case: true
  word: true
- trigger: etre
  replace: "\xEAtre"
  propagate_case: true
  word: true
- trigger: experimental
  replace: "exp\xE9rimental"
  propagate_case: true
  word: true
- trigger: fachisme
  replace: fascisme
  propagate_case: true
  word: true
- trigger: fachismes
  replace: fascismes
  propagate_case: true
  word: true
- trigger: fachiste
  replace: fasciste
  propagate_case: true
  word: true
- trigger: fachistes
  replace: fascistes
  propagate_case: true
  word: true
- trigger: flotille
  replace: flottille
  propagate_case: true
  word: true
- trigger: flotilles
  replace: flotrilles
  propagate_case: true
  word: true
- trigger: "f\u0153hn"
  replace: foehn
  propagate_case: true
  word: true
- trigger: Guyana
  replace: Guiana
  propagate_case: true
  word: true
- trigger: "i\xE7i"
  replace: ici
  propagate_case: true
  word: true
- trigger: "il\xF4t"
  replace: "\xEElot"
  propagate_case: true
  word: true
- trigger: inclu
  replace: inclus
  propagate_case: true
  word: true
- trigger: "Isra\xEBlien"
  replace: "Isra\xE9lien"
  propagate_case: true
  word: true
- trigger: "Isra\xEBliens"
  replace: "Isra\xE9liens"
  propagate_case: true
  word: true
- trigger: lipofucsine
  replace: lipofuscine
  propagate_case: true
  word: true
- trigger: "mer\xE7i"
  replace: merci
  propagate_case: true
  word: true
- trigger: merveilleu
  replace: merveilleux
  propagate_case: true
  word: true
- trigger: nivau
  replace: niveau
  propagate_case: true
  word: true
- trigger: par ci
  replace: par-ci
  propagate_case: true
  word: true
- trigger: par la
  replace: par-la
  propagate_case: true
  word: true
- trigger: "patin \xE0 roues"
  replace: "patin \xE0 roulettes"
  propagate_case: true
  word: true
- trigger: "pendre la cr\xE9malli\xE8re"
  replace: "pendre la cr\xE9maill\xE8re"
  propagate_case: true
  word: true
- trigger: "peut \xEAtre"
  replace: "peut-\xEAtre"
  propagate_case: true
  word: true
- trigger: pouasse
  replace: poisse
  propagate_case: true
  word: true
- trigger: pourpalers
  replace: pourparlers
  propagate_case: true
  word: true
- trigger: "prot\xE9ge"
  replace: "prot\xE8ge"
  propagate_case: true
  word: true
- trigger: "qualit\xE9e"
  replace: "qualit\xE9"
  propagate_case: true
  word: true
- trigger: "r\xF4der"
  replace: roder
  propagate_case: true
  word: true
- trigger: saynette
  replace: "sayn\xE8te"
  propagate_case: true
  word: true
- trigger: soit-disant
  replace: soi-disant
  propagate_case: true
  word: true
- trigger: transexuel
  replace: transsexuel
  propagate_case: true
  word: true
- trigger: transexuels
  replace: transsexuels
  propagate_case: true
  word: true
- trigger: trompe l'oeil
  replace: "trompe-l\u2019\u0153il"
  propagate_case: true
  word: true
