# openai package
# Query chat-gpt anywhere from your computer

matches:

  - trigger: ":ask-gpt"
    replace: "{{output}}"
    vars:
      - name: "clipboard"
        type: "clipboard"
      - name: output
        type: shell
        params:
          cmd: 'bash $CONFIG/match/packages/openai/openai.sh "{{clipboard}}" 1.0'

  - trigger: ":respond"
    replace: "{{output}}"
    vars:
      - name: "clipboard"
        type: "clipboard"
      - name: output
        type: shell
        params:
          cmd: 'bash $CONFIG/match/packages/openai/openai.sh "Write a response to: {{clipboard}}" 1.0'

  - trigger: ":explain"
    replace: "{{output}}"
    vars:
      - name: "clipboard"
        type: "clipboard"
      - name: output
        type: shell
        params:
          cmd: 'bash $CONFIG/match/packages/openai/openai.sh "Explain in detail: {{clipboard}}" 1.0'

  - trigger: ":eli5"
    replace: "{{output}}"
    vars:
      - name: "clipboard"
        type: "clipboard"
      - name: output
        type: shell
        params:
          cmd: 'bash $CONFIG/match/packages/openai/openai.sh "Explain like I am 5: {{clipboard}}" 1.0'

  - trigger: ":summarize"
    replace: "{{output}}"
    vars:
      - name: "clipboard"
        type: "clipboard"
      - name: output
        type: shell
        params:
          cmd: 'bash $CONFIG/match/packages/openai/openai.sh "Summarize: {{clipboard}}" 1.0'

  - trigger: ":write"
    replace: "{{output}}"
    vars:
      - name: "clipboard"
        type: "clipboard"
      - name: output
        type: shell
        params:
          cmd: 'bash $CONFIG/match/packages/openai/openai.sh "Write an article on: {{clipboard}}" 1.0'

  - trigger: ":debug"
    replace: "{{output}}"
    vars:
      - name: "clipboard"
        type: "clipboard"
      - name: output
        type: shell
        params:
          cmd: 'bash $CONFIG/match/packages/openai/openai.sh "Debug the following code: {{clipboard}}" 1.0'

  - trigger: ":grade"
    replace: "{{output}}"
    vars:
      - name: "clipboard"
        type: "clipboard"
      - name: output
        type: shell
        params:
          cmd: 'bash $CONFIG/match/packages/openai/openai.sh "Grade the following part of an essay: {{clipboard}}" 1.0'

  - trigger: ":rephrase"
    replace: "{{output}}"
    vars:
      - name: "clipboard"
        type: "clipboard"
      - name: output
        type: shell
        params:
          cmd: 'bash $CONFIG/match/packages/openai/openai.sh "Rephrase and correct grammatical errors in: {{clipboard}}" 1.0'

  - trigger: ":correct"
    replace: "{{output}}"
    vars:
      - name: "clipboard"
        type: "clipboard"
      - name: output
        type: shell
        params:
          cmd: 'bash $CONFIG/match/packages/openai/openai.sh "Correct grammatical errors in: {{clipboard}}" 1.0'

  # Lower temperature (0.2) used for fact checking.
  - trigger: ":fact-check"
    replace: "{{output}}"
    vars:
      - name: "clipboard"
        type: "clipboard"
      - name: output
        type: shell
        params:
          cmd: 'bash $CONFIG/match/packages/openai/openai.sh "Check this fact: {{clipboard}}" 0.2'

  # regex based openai query
  # Low char limit because of Espanso's 30 character limit on regex.
  - regex: ":Q/(?P<query>.*)//"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: 'bash $CONFIG/match/packages/openai/openai.sh "{{query}}" 1.0'