matches:  
  - trigger: ":Ac"
    replace: "Actinium"
  - trigger: ":Al"
    replace: "Aluminum"
  - trigger: ":Am"
    replace: "Americium"
  - trigger: ":Sb"
    replace: "Antimony"
  - trigger: ":Ar"
    replace: "Argon"
  - trigger: ":As"
    replace: "Arsenic"
  - trigger: ":At"
    replace: "Astatine"
  - trigger: ":Ba"
    replace: "Barium"
  - trigger: ":Bk"
    replace: "Berkelium"
  - trigger: ":Be"
    replace: "Beryllium"
  - trigger: ":Bi"
    replace: "Bismuth"
  - trigger: ":Bh"
    replace: "Bohrium"
  - trigger: ":B"
    replace: "Boron"
  - trigger: ":Br"
    replace: "Bromine"
  - trigger: ":Cd"
    replace: "Cadmium"
  - trigger: ":Ca"
    replace: "Calcium"
  - trigger: ":Cf"
    replace: "Californium"
  - trigger: ":C"
    replace: "Carbon"
  - trigger: ":Ce"
    replace: "Cerium"
  - trigger: ":Cs"
    replace: "Cesium"
  - trigger: ":Cl"
    replace: "Chlorine"
  - trigger: ":Cr"
    replace: "Chromium"
  - trigger: ":Co"
    replace: "Cobalt"
  - trigger: ":Cn"
    replace: "Copernicium"
  - trigger: ":Cu"
    replace: "Copper"
  - trigger: ":Cm"
    replace: "Curium"
  - trigger: ":Ds"
    replace: "Darmstadtium"
  - trigger: ":Db"
    replace: "Dubnium"
  - trigger: ":Dy"
    replace: "Dysprosium"
  - trigger: ":Es"
    replace: "Einsteinium"
  - trigger: ":Er"
    replace: "Erbium"
  - trigger: ":Eu"
    replace: "Europium"
  - trigger: ":Fm"
    replace: "Fermium"
  - trigger: ":Fl"
    replace: "Flerovium "
  - trigger: ":F"
    replace: "Fluorine"
  - trigger: ":Fr"
    replace: "Francium"
  - trigger: ":Gd"
    replace: "Gadolinium"
  - trigger: ":Ga"
    replace: "Gallium"
  - trigger: ":Ge"
    replace: "Germanium"
  - trigger: ":Au"
    replace: "Gold"
  - trigger: ":Hf"
    replace: "Hafnium"
  - trigger: ":Hs"
    replace: "Hassium"
  - trigger: ":He"
    replace: "Helium"
  - trigger: ":Ho"
    replace: "Holmium"
  - trigger: ":H"
    replace: "Hydrogen"
  - trigger: ":In"
    replace: "Indium"
  - trigger: ":I"
    replace: "Iodine"
  - trigger: ":Ir"
    replace: "Iridium"
  - trigger: ":Fe"
    replace: "Iron"
  - trigger: ":Kr"
    replace: "Krypton"
  - trigger: ":La"
    replace: "Lanthanum"
  - trigger: ":Lr"
    replace: "Lawrencium"
  - trigger: ":Pb"
    replace: "Lead"
  - trigger: ":Li"
    replace: "Lithium"
  - trigger: ":Lv"
    replace: "Livermorium "
  - trigger: ":Lu"
    replace: "Lutetium"
  - trigger: ":Mg"
    replace: "Magnesium"
  - trigger: ":Mn"
    replace: "Manganese"
  - trigger: ":Mt"
    replace: "Meitnerium"
  - trigger: ":Md"
    replace: "Mendelevium"
  - trigger: ":Hg"
    replace: "Mercury"
  - trigger: ":Mo"
    replace: "Molybdenum"
  - trigger: ":Mc"
    replace: "Moscovium "
  - trigger: ":Nd"
    replace: "Neodymium"
  - trigger: ":Ne"
    replace: "Neon"
  - trigger: ":Np"
    replace: "Neptunium"
  - trigger: ":Ni"
    replace: "Nickel"
  - trigger: ":Nh"
    replace: "Nihonium "
  - trigger: ":Nb"
    replace: "Niobium"
  - trigger: ":N"
    replace: "Nitrogen"
  - trigger: ":No"
    replace: "Nobelium"
  - trigger: ":Og"
    replace: "Oganesson "
  - trigger: ":Os"
    replace: "Osmium"
  - trigger: ":O"
    replace: "Oxygen"
  - trigger: ":Pd"
    replace: "Palladium"
  - trigger: ":P"
    replace: "Phosphorus"
  - trigger: ":Pt"
    replace: "Platinum"
  - trigger: ":Pu"
    replace: "Plutonium"
  - trigger: ":Po"
    replace: "Polonium"
  - trigger: ":K"
    replace: "Potassium"
  - trigger: ":Pr"
    replace: "Praseodymium"
  - trigger: ":Pm"
    replace: "Promethium"
  - trigger: ":Pa"
    replace: "Protactinium"
  - trigger: ":Ra"
    replace: "Radium"
  - trigger: ":Rn"
    replace: "Radon"
  - trigger: ":Re"
    replace: "Rhenium"
  - trigger: ":Rh"
    replace: "Rhodium"
  - trigger: ":Rg"
    replace: "Roentgenium"
  - trigger: ":Rb"
    replace: "Rubidium"
  - trigger: ":Ru"
    replace: "Ruthenium"
  - trigger: ":Rf"
    replace: "Rutherfordium"
  - trigger: ":Sm"
    replace: "Samarium"
  - trigger: ":Sc"
    replace: "Scandium"
  - trigger: ":Sg"
    replace: "Seaborgium"
  - trigger: ":Se"
    replace: "Selenium"
  - trigger: ":Si"
    replace: "Silicon"
  - trigger: ":Ag"
    replace: "Silver"
  - trigger: ":Na"
    replace: "Sodium"
  - trigger: ":Sr"
    replace: "Strontium"
  - trigger: ":S"
    replace: "Sulfur"
  - trigger: ":Ta"
    replace: "Tantalum"
  - trigger: ":Tc"
    replace: "Technetium"
  - trigger: ":Te"
    replace: "Tellurium"
  - trigger: ":Ts"
    replace: "Tennessine "
  - trigger: ":Tb"
    replace: "Terbium"
  - trigger: ":Tl"
    replace: "Thallium"
  - trigger: ":Th"
    replace: "Thorium"
  - trigger: ":Tm"
    replace: "Thulium"
  - trigger: ":Sn"
    replace: "Tin"
  - trigger: ":Ti"
    replace: "Titanium"
  - trigger: ":W"
    replace: "Tungsten"
  - trigger: ":U"
    replace: "Uranium"
  - trigger: ":V"
    replace: "Vanadium"
  - trigger: ":Xe"
    replace: "Xenon"
  - trigger: ":Yb"
    replace: "Ytterbium"
  - trigger: ":Y"
    replace: "Yttrium"
  - trigger: ":Zn"
    replace: "Zinc"
  - trigger: ":Zr"
    replace: "Zirconium"
