matches:
  - trigger: "\\\\bbA"
    replace: "ğ”¸"
  - trigger: "\\\\bbB"
    replace: "ğ”¹"
  - trigger: "\\\\bbC"
    replace: "â„‚"
  - trigger: "\\\\bbD"
    replace: "ğ”»"
  - trigger: "\\\\bbE"
    replace: "ğ”¼"
  - trigger: "\\\\bbF"
    replace: "ğ”½"
  - trigger: "\\\\bbG"
    replace: "ğ”¾"
  - trigger: "\\\\bbH"
    replace: "â„"
  - trigger: "\\\\bbI"
    replace: "ğ•€"
  - trigger: "\\\\bbJ"
    replace: "ğ•"
  - trigger: "\\\\bbK"
    replace: "ğ•‚"
  - trigger: "\\\\bbL"
    replace: "ğ•ƒ"
  - trigger: "\\\\bbM"
    replace: "ğ•„"
  - trigger: "\\\\bbN"
    replace: "â„•"
  - trigger: "\\\\bbO"
    replace: "ğ•†"
  - trigger: "\\\\bbP"
    replace: "â„™"
  - trigger: "\\\\bbQ"
    replace: "â„š"
  - trigger: "\\\\bbR"
    replace: "â„"
  - trigger: "\\\\bbS"
    replace: "ğ•Š"
  - trigger: "\\\\bbT"
    replace: "ğ•‹"
  - trigger: "\\\\bbU"
    replace: "ğ•Œ"
  - trigger: "\\\\bbV"
    replace: "ğ•"
  - trigger: "\\\\bbW"
    replace: "ğ•"
  - trigger: "\\\\bbX"
    replace: "ğ•"
  - trigger: "\\\\bbY"
    replace: "ğ•"
  - trigger: "\\\\bbZ"
    replace: "â„¤"
  - trigger: "\\\\bba"
    replace: "ğ•’"
  - trigger: "\\\\bbb"
    replace: "ğ•“"
  - trigger: "\\\\bbc"
    replace: "ğ•”"
  - trigger: "\\\\bbd"
    replace: "ğ••"
  - trigger: "\\\\bbe"
    replace: "ğ•–"
  - trigger: "\\\\bbf"
    replace: "ğ•—"
  - trigger: "\\\\bbg"
    replace: "ğ•˜"
  - trigger: "\\\\bbh"
    replace: "ğ•™"
  - trigger: "\\\\bbi"
    replace: "ğ•š"
  - trigger: "\\\\bbj"
    replace: "ğ•›"
  - trigger: "\\\\bbk"
    replace: "ğ•œ"
  - trigger: "\\\\bbl"
    replace: "ğ•"
  - trigger: "\\\\bbm"
    replace: "ğ•"
  - trigger: "\\\\bbn"
    replace: "ğ•Ÿ"
  - trigger: "\\\\bbo"
    replace: "ğ• "
  - trigger: "\\\\bbp"
    replace: "ğ•¡"
  - trigger: "\\\\bbq"
    replace: "ğ•¢"
  - trigger: "\\\\bbr"
    replace: "ğ•£"
  - trigger: "\\\\bbs"
    replace: "ğ•¤"
  - trigger: "\\\\bbt"
    replace: "ğ•¥"
  - trigger: "\\\\bbu"
    replace: "ğ•¦"
  - trigger: "\\\\bbv"
    replace: "ğ•§"
  - trigger: "\\\\bbw"
    replace: "ğ•¨"
  - trigger: "\\\\bbx"
    replace: "ğ•©"
  - trigger: "\\\\bby"
    replace: "ğ•ª"
  - trigger: "\\\\bbz"
    replace: "ğ•«"
