# 2022-03-12T12:00:49+0000
# salopst
# 
# Some Espanso triggers for Hugo Shortcodes
# https://gohugo.io/content-management/shortcodes/


matches:
  - trigger: ":hf"
    replace: "{{< figure src=\"$|$\" title=\"FIGURE_TITLE\" >}}"

  - trigger: ":hg"
    replace: "{{< gist GIT_USER_NAME GIST_ID >}}"

  - trigger: ":hil"
    replace: |-
      {{< highlight $|$SYNTAX_LANG >}}

      {{< /highlight >}}

  - trigger: ":hin"
    replace: "{{< instagram $|$INSTAGRAM_ID hidecaption >}}"

  - trigger: ":hp"
    replace: "{{< param $|$PARAMETER_NAME >}}"

    # generates absolute href
  - trigger: ":href"
    replace: "{{< ref \"$|$ANCHOR_TARGET\" >}}"

    # generates relative href
  - trigger: ":hrel"
    replace: "{{< relref \"$|$ANCHOR_TARGET\" >}}"

  - trigger: ":ht"
    replace: "{{< tweet user=\"$|$\" id=\"TWEET_ID\" >}}"

  - trigger: ":hv"
    replace: "{{< vimeo $|$VIMEO_ID >}}"

  - trigger: ":hy"
    replace: "{{< youtube id=\"$|$YOUTUBE_ID\" title=\"VIDEO_TITLE\" autoplay=\"TRUE_|_FALSE\" >}}"

  - trigger: ":him"
    replace: "{{< image src=\"/uploads/$|$IMAGE_FILE_NAME\" alt=\"ALT_TEXT\" position=\"center\" style=\"border-radius: 30px;\" >}}"