# Made by Ivan Bue @soulllink
# This package made for simple math 

matches:
  - trigger: "\\fr "
    replace: "\\frac{$|$}{}"
  - trigger: "\\sys "
    replace: "\\begin{cases}$|$\\end{cases}"
  - trigger: "\\cd "
    replace: "\\cdot"
  - trigger: "\\quad "
    replace: "\\[x=\\frac{-b\\pm\\sqrt{b^2-4ac}}{2a}\\]"
  - trigger: "\\sq "
    replace: "\\sqrt{x}"
  - trigger: "\\log "
    replace: "\\log_{a}b"
  - trigger: "\\vec "
    replace: "\\vec{$|$}"
  - trigger: "\\matrix "
    replace: "\\left[\\begin{array}{ccc}1 & 2 & 3 \\\\ 4 & 5 & 6\\\\ 7 & 8 & 0 \\end{array} \\right]"
  - trigger: "\\deter "
    replace: "\\left|\\begin{array}{ccc}1 & 2 & 3 \\\\ 4 & 5 & 6\\\\ 7 & 8 & 0 \\end{array} \\right|"
  - trigger: "\\cer "
    replace: "^{\\circ}"
  - trigger: "\\cup "
    replace: "\\bigcup_{n=1}^{10}A_n"
  - trigger: "\\cap "
    replace: "\\bigcap_{n=1}^{10}A_n"
  - trigger: "\\list "
    replace: "\\begin{itemize}\\ $|$ \\end{itemize}"
  - trigger: "\\nlist "
    replace: "\\begin{enumerate}\\ $|$ \\end{enumerate}"