global_vars:
  - name: sep
    type: script
    params:
      args:
        - python
        - -c
        - |
          import os

          print(os.path.sep)

matches:
  - trigger: ":img-morning"
    image_path: "$CONFIG{{sep}}match{{sep}}packages{{sep}}good-morning{{sep}}resources{{sep}}tmp.gif"

  - trigger: ":morning"
    replace: "{{output}}"
    vars:
      - name: output
        type: script
        params:
          args:
            - python
            - "%CONFIG%{{sep}}match{{sep}}packages{{sep}}good-morning{{sep}}resources{{sep}}good_morning.py"