matches:
  - trigger: "s,"
    replace: "ș"
  - trigger: "S,"
    replace: "Ș"
  - trigger: "t,"
    replace: "ț"
  - trigger: "T,"
    replace: "Ț"
  - trigger: "i^"
    replace: "î"
  - trigger: "I^"
    replace: "Î"
  - trigger: "a^"
    replace: "â"
  - trigger: "A^"
    replace: "Â"
  - trigger: "a~"
    replace: "ă"
  - trigger: "A~"
    replace: "Ă"
