matches:
  - trigger: ":urle"
    replace: "{{output}}"
    vars:
      - name: "clipboard"
        type: "clipboard"
      - name: output
        type: script
        params:
          args: 
            - python
            - -c
            - |
               from urllib.parse import quote_plus
               import sys
               sys.stdout.reconfigure(encoding='utf-8')
               print(quote_plus({{clipboard}}),end='')
          trim: false
  - trigger: ":urld"
    replace: "{{output}}"
    vars:
      - name: "clipboard"
        type: "clipboard"
      - name: output
        type: script
        params:
          args: 
            - python
            - -c
            - |
               from urllib.parse import unquote
               import sys
               sys.stdout.reconfigure(encoding='utf-8')
               print(unquote({{clipboard}}),end='')
          trim: false
