# Greek Letters

matches:
  # LIST ALL LETTERS
  - trigger: ":greeks"
    replace: "Alpha:   Αα\nBeta:    Ββ\nDelta:   Δδ\nEpsilon: Εε\nPhi:     Φφ\nGamma:   Γγ\nEta:     Ηη\nIota:    Ιι\nTheta:   Θθ\nKappa:   Κκ\nLambda:  Λλ\nMu:      Μμ\nNu:      Νν\nOmicron: Οο\nPi:      Ππ\nChi:     Χχ\nRho:     Ρρ\nSigma:   Σσ\nTau:     Ττ\nUpsilon: Υυ\nOmega:   Ωω\nXi:      Ξξ\nPsi:     Ψψ\nZeta:    Ζζ"
    
  - trigger: ":Greeks"
    replace: "Alpha:   Αα\nBeta:    Ββ\nDelta:   Δδ\nEpsilon: Εε\nPhi:     Φφ\nGamma:   Γγ\nEta:     Ηη\nIota:    Ιι\nTheta:   Θθ\nKappa:   Κκ\nLambda:  Λλ\nMu:      Μμ\nNu:      Νν\nOmicron: Οο\nPi:      Ππ\nChi:     Χχ\nRho:     Ρρ\nSigma:   Σσ\nTau:     Ττ\nUpsilon: Υυ\nOmega:   Ωω\nXi:      Ξξ\nPsi:     Ψψ\nZeta:    Ζζ"

  # GREEK CAPITAL LETTER ALPHA
  - trigger: ":Alpha"
    replace: "Α"

  # GREEK SMALL LETTER ALPHA
  - trigger: ":alpha"
    replace: "α"

  # GREEK CAPITAL LETTER BETA
  - trigger: ":Beta"
    replace: "Β"

  # GREEK SMALL LETTER BETA
  - trigger: ":beta"
    replace: "β"

  # GREEK CAPITAL LETTER DELTA
  - trigger: ":Delta"
    replace: "Δ"

  # GREEK SMALL LETTER DELTA
  - trigger: ":delta"
    replace: "δ"

  # GREEK CAPITAL LETTER EPSILON
  - trigger: ":Epsilon"
    replace: "Ε"

  # GREEK SMALL LETTER EPSILON
  - trigger: ":epsilon"
    replace: "ε"

  # GREEK CAPITAL LETTER PHI
  - trigger: ":Phi"
    replace: "Φ"

  # GREEK SMALL LETTER PHI
  - trigger: ":phi"
    replace: "φ"

  # GREEK CAPITAL LETTER GAMMA
  - trigger: ":Gamma"
    replace: "Γ"

  # GREEK SMALL LETTER GAMMA
  - trigger: ":gamma"
    replace: "γ"

  # GREEK CAPITAL LETTER ETA
  - trigger: ":Eta"
    replace: "Η"

  # GREEK SMALL LETTER ETA
  - trigger: ":eta"
    replace: "η"

  # GREEK CAPITAL LETTER IOTA
  - trigger: ":Iota"
    replace: "Ι"

  # GREEK SMALL LETTER IOTA
  - trigger: ":iota"
    replace: "ι"

  # GREEK CAPITAL LETTER THETA
  - trigger: ":Theta"
    replace: "Θ"

  # GREEK SMALL LETTER THETA
  - trigger: ":theta"
    replace: "θ"

  # GREEK CAPITAL LETTER KAPPA
  - trigger: ":Kappa"
    replace: "Κ"

  # GREEK SMALL LETTER KAPPA
  - trigger: ":kappa"
    replace: "κ"

  # GREEK CAPITAL LETTER LAMDA
  - trigger: ":Lambda"
    replace: "Λ"

  # GREEK SMALL LETTER LAMDA
  - trigger: ":lambda"
    replace: "λ"

  # GREEK CAPITAL LETTER MU
  - trigger: ":Mu"
    replace: "Μ"

  # GREEK SMALL LETTER MU
  - trigger: ":mu"
    replace: "μ"

  # GREEK CAPITAL LETTER NU
  - trigger: ":Nu"
    replace: "Ν"

  # GREEK SMALL LETTER NU
  - trigger: ":nu"
    replace: "ν"

  # GREEK CAPITAL LETTER OMICRON
  - trigger: ":Omicron"
    replace: "Ο"

  # GREEK SMALL LETTER OMICRON
  - trigger: ":omicron"
    replace: "ο"

  # GREEK CAPITAL LETTER PI
  - trigger: ":Pi"
    replace: "Π"

  # GREEK SMALL LETTER PI
  - trigger: ":pi"
    replace: "π"

  # GREEK CAPITAL LETTER CHI
  - trigger: ":Chi"
    replace: "Χ"

  # GREEK SMALL LETTER CHI
  - trigger: ":chi"
    replace: "χ"

  # GREEK CAPITAL LETTER RHO
  - trigger: ":Rho"
    replace: "Ρ"

  # GREEK SMALL LETTER RHO
  - trigger: ":rho"
    replace: "ρ"

  # GREEK CAPITAL LETTER SIGMA
  - trigger: ":Sigma"
    replace: "Σ"

  # GREEK SMALL LETTER SIGMA
  - trigger: ":sigma"
    replace: "σ"

  # GREEK CAPITAL LETTER TAU
  - trigger: ":Tau"
    replace: "Τ"

  # GREEK SMALL LETTER TAU
  - trigger: ":tau"
    replace: "τ"

  # GREEK CAPITAL LETTER UPSILON
  - trigger: ":Upsilon"
    replace: "Υ"

  # GREEK SMALL LETTER UPSILON
  - trigger: ":upsilon"
    replace: "υ"

  # GREEK CAPITAL LETTER OMEGA
  - trigger: ":Omega"
    replace: "Ω"

  # GREEK SMALL LETTER OMEGA
  - trigger: ":omega"
    replace: "ω"

  # GREEK CAPITAL LETTER XI
  - trigger: ":Xi"
    replace: "Ξ"

  # GREEK SMALL LETTER XI
  - trigger: ":xi"
    replace: "ξ"

  # GREEK CAPITAL LETTER PSI
  - trigger: ":Psi"
    replace: "Ψ"

  # GREEK SMALL LETTER PSI
  - trigger: ":psi"
    replace: "ψ"

  # GREEK CAPITAL LETTER ZETA
  - trigger: ":Zeta"
    replace: "Ζ"

  # GREEK SMALL LETTER ZETA
  - trigger: ":zeta"
    replace: "ζ"
