matches:
- replace: "\U0001F3A8"
  trigger: ':art:'
- replace: "\u26A1\uFE0F"
  trigger: ':zap:'
- replace: "\U0001F525"
  trigger: ':fire:'
- replace: "\U0001F41B"
  trigger: ':bug:'
- replace: "\U0001F691"
  trigger: ':ambulance:'
- replace: "\u2728"
  trigger: ':sparkles:'
- replace: "\U0001F4DD"
  trigger: ':pencil:'
- replace: "\U0001F680"
  trigger: ':rocket:'
- replace: "\U0001F484"
  trigger: ':lipstick:'
- replace: "\U0001F389"
  trigger: ':tada:'
- replace: "\u2705"
  trigger: ':white_check_mark:'
- replace: "\U0001F512"
  trigger: ':lock:'
- replace: "\U0001F516"
  trigger: ':bookmark:'
- replace: "\U0001F6A8"
  trigger: ':rotating_light:'
- replace: "\U0001F6A7"
  trigger: ':construction:'
- replace: "\U0001F49A"
  trigger: ':green_heart:'
- replace: "\u2B07\uFE0F"
  trigger: ':arrow_down:'
- replace: "\u2B06\uFE0F"
  trigger: ':arrow_up:'
- replace: "\U0001F4CC"
  trigger: ':pushpin:'
- replace: "\U0001F477"
  trigger: ':construction_worker:'
- replace: "\U0001F4C8"
  trigger: ':chart_with_upwards_trend:'
- replace: "\u267B\uFE0F"
  trigger: ':recycle:'
- replace: "\u2795"
  trigger: ':heavy_plus_sign:'
- replace: "\u2796"
  trigger: ':heavy_minus_sign:'
- replace: "\U0001F527"
  trigger: ':wrench:'
- replace: "\U0001F528"
  trigger: ':hammer:'
- replace: "\U0001F310"
  trigger: ':globe_with_meridians:'
- replace: "\u270F\uFE0F"
  trigger: ':pencil2:'
- replace: "\U0001F4A9"
  trigger: ':poop:'
- replace: "\u23EA"
  trigger: ':rewind:'
- replace: "\U0001F500"
  trigger: ':twisted_rightwards_arrows:'
- replace: "\U0001F4E6"
  trigger: ':package:'
- replace: "\U0001F47D"
  trigger: ':alien:'
- replace: "\U0001F69A"
  trigger: ':truck:'
- replace: "\U0001F4C4"
  trigger: ':page_facing_up:'
- replace: "\U0001F4A5"
  trigger: ':boom:'
- replace: "\U0001F371"
  trigger: ':bento:'
- replace: "\u267F\uFE0F"
  trigger: ':wheelchair:'
- replace: "\U0001F4A1"
  trigger: ':bulb:'
- replace: "\U0001F37B"
  trigger: ':beers:'
- replace: "\U0001F4AC"
  trigger: ':speech_balloon:'
- replace: "\U0001F5C3"
  trigger: ':card_file_box:'
- replace: "\U0001F50A"
  trigger: ':loud_sound:'
- replace: "\U0001F507"
  trigger: ':mute:'
- replace: "\U0001F465"
  trigger: ':busts_in_silhouette:'
- replace: "\U0001F6B8"
  trigger: ':children_crossing:'
- replace: "\U0001F3D7"
  trigger: ':building_construction:'
- replace: "\U0001F4F1"
  trigger: ':iphone:'
- replace: "\U0001F921"
  trigger: ':clown_face:'
- replace: "\U0001F95A"
  trigger: ':egg:'
- replace: "\U0001F648"
  trigger: ':see_no_evil:'
- replace: "\U0001F4F8"
  trigger: ':camera_flash:'
- replace: "\u2697"
  trigger: ':alembic:'
- replace: "\U0001F50D"
  trigger: ':mag:'
- replace: "\U0001F3F7\uFE0F"
  trigger: ':label:'
- replace: "\U0001F331"
  trigger: ':seedling:'
- replace: "\U0001F6A9"
  trigger: ':triangular_flag_on_post:'
- replace: "\U0001F945"
  trigger: ':goal_net:'
- replace: "\U0001F4AB"
  trigger: ':dizzy:'
- replace: "\U0001F5D1"
  trigger: ':wastebasket:'
