matches:
  - trigger: ":not"
    replace: "¬"
  - trigger: ":and"
    replace: "∧"
  - trigger: ":or"
    replace: "∨"
  - trigger: ":xor"
    replace: "⊕"
  - trigger: ":imp"
    replace: "→"
  - trigger: ":biimp"
    replace: "⟷"
  - trigger: ":eq"
    replace: "≡"
  - trigger: ":true"
    replace: "⊤"
  - trigger: ":false"
    replace: "⊥"
  - trigger: ":all"
    replace: "∀"
  - trigger: ":exists"
    replace: "∃"
