matches:
  - trigger: ":not"
    replace: "¬"
  - trigger: ":and"
    replace: "∧"
  - trigger: ":or"
    replace: "∨"
  - trigger: ":xor"
    replace: "⊕"
  - triggers: [":imp", ":if"]
    replace: "→"
  - triggers: [":bimp", ":iff"]
    replace: "↔"
  - triggers: [":eq", ":def"]
    replace: "≡"
  - triggers: [":true", ":top"]
    replace: "⊤"
  - triggers: [":false", ":bot"]
    replace: "⊥"
  - trigger: ":forall"
    replace: "∀"
  - trigger: ":exists"
    replace: "∃"
  - trigger: ":proves"
    replace: "⊢"
  - trigger: ":models"
    replace: "⊨"
