matches:
  - trigger: ":gitmoji"
    replace: "{{output}}"
    vars:
      - name: output
        type: choice
        params:
          values:
            - label: "🎨 :art: Improve structure / format of the code."
              id: "🎨"
            - label: "⚡️ :zap: Improve performance."
              id: "⚡️"
            - label: "🔥 :fire: Remove code or files."
              id: "🔥"
            - label: "🐛 :bug: Fix a bug."
              id: "🐛"
            - label: "🚑️ :ambulance: Critical hotfix."
              id: "🚑️"
            - label: "✨ :sparkles: Introduce new features."
              id: "✨"
            - label: "📝 :memo: Add or update documentation."
              id: "📝"
            - label: "🚀 :rocket: Deploy stuff."
              id: "🚀"
            - label: "💄 :lipstick: Add or update the UI and style files."
              id: "💄"
            - label: "🎉 :tada: Begin a project."
              id: "🎉"
            - label: "✅ :white_check_mark: Add, update, or pass tests."
              id: "✅"
            - label: "🔒️ :lock: Fix security or privacy issues."
              id: "🔒️"
            - label: "🔐 :closed_lock_with_key: Add or update secrets."
              id: "🔐"
            - label: "🔖 :bookmark: Release / Version tags."
              id: "🔖"
            - label: "🚨 :rotating_light: Fix compiler / linter warnings."
              id: "🚨"
            - label: "🚧 :construction: Work in progress."
              id: "🚧"
            - label: "💚 :green_heart: Fix CI Build."
              id: "💚"
            - label: "⬇️ :arrow_down: Downgrade dependencies."
              id: "⬇️"
            - label: "⬆️ :arrow_up: Upgrade dependencies."
              id: "⬆️"
            - label: "📌 :pushpin: Pin dependencies to specific versions."
              id: "📌"
            - label: "👷 :construction_worker: Add or update CI build system."
              id: "👷"
            - label: "📈 :chart_with_upwards_trend: Add or update analytics or track code."
              id: "📈"
            - label: "♻️ :recycle: Refactor code."
              id: "♻️"
            - label: "➕ :heavy_plus_sign: Add a dependency."
              id: "➕"
            - label: "➖ :heavy_minus_sign: Remove a dependency."
              id: "➖"
            - label: "🔧 :wrench: Add or update configuration files."
              id: "🔧"
            - label: "🔨 :hammer: Add or update development scripts."
              id: "🔨"
            - label: "🌐 :globe_with_meridians: Internationalization and localization."
              id: "🌐"
            - label: "✏️ :pencil2: Fix typos."
              id: "✏️"
            - label: "💩 :poop: Write bad code that needs to be improved."
              id: "💩"
            - label: "⏪️ :rewind: Revert changes."
              id: "⏪️"
            - label: "🔀 :twisted_rightwards_arrows: Merge branches."
              id: "🔀"
            - label: "📦️ :package: Add or update compiled files or packages."
              id: "📦️"
            - label: "👽️ :alien: Update code due to external API changes."
              id: "👽️"
            - label: "🚚 :truck: Move or rename resources (e.g.: files, paths, routes)."
              id: "🚚"
            - label: "📄 :page_facing_up: Add or update license."
              id: "📄"
            - label: "💥 :boom: Introduce breaking changes."
              id: "💥"
            - label: "🍱 :bento: Add or update assets."
              id: "🍱"
            - label: "♿️ :wheelchair: Improve accessibility."
              id: "♿️"
            - label: "💡 :bulb: Add or update comments in source code."
              id: "💡"
            - label: "🍻 :beers: Write code drunkenly."
              id: "🍻"
            - label: "💬 :speech_balloon: Add or update text and literals."
              id: "💬"
            - label: "🗃️ :card_file_box: Perform database related changes."
              id: "🗃️"
            - label: "🔊 :loud_sound: Add or update logs."
              id: "🔊"
            - label: "🔇 :mute: Remove logs."
              id: "🔇"
            - label: "👥 :busts_in_silhouette: Add or update contributor(s)."
              id: "👥"
            - label: "🚸 :children_crossing: Improve user experience / usability."
              id: "🚸"
            - label: "🏗️ :building_construction: Make architectural changes."
              id: "🏗️"
            - label: "📱 :iphone: Work on responsive design."
              id: "📱"
            - label: "🤡 :clown_face: Mock things."
              id: "🤡"
            - label: "🥚 :egg: Add or update an easter egg."
              id: "🥚"
            - label: "🙈 :see_no_evil: Add or update a .gitignore file."
              id: "🙈"
            - label: "📸 :camera_flash: Add or update snapshots."
              id: "📸"
            - label: "⚗️ :alembic: Perform experiments."
              id: "⚗️"
            - label: "🔍️ :mag: Improve SEO."
              id: "🔍️"
            - label: "🏷️ :label: Add or update types."
              id: "🏷️"
            - label: "🌱 :seedling: Add or update seed files."
              id: "🌱"
            - label: "🚩 :triangular_flag_on_post: Add, update, or remove feature flags."
              id: "🚩"
            - label: "🥅 :goal_net: Catch errors."
              id: "🥅"
            - label: "💫 :dizzy: Add or update animations and transitions."
              id: "💫"
            - label: "🗑️ :wastebasket: Deprecate code that needs to be cleaned up."
              id: "🗑️"
            - label: "🛂 :passport_control: Work on code related to authorization, roles and permissions."
              id: "🛂"
            - label: "🩹 :adhesive_bandage: Simple fix for a non-critical issue."
              id: "🩹"
            - label: "🧐 :monocle_face: Data exploration/inspection."
              id: "🧐"
            - label: "⚰️ :coffin: Remove dead code."
              id: "⚰️"
            - label: "🧪 :test_tube: Add a failing test."
              id: "🧪"
            - label: "👔 :necktie: Add or update business logic."
              id: "👔"
            - label: "🩺 :stethoscope: Add or update healthcheck."
              id: "🩺"
            - label: "🧱 :bricks: Infrastructure related changes."
              id: "🧱"
            - label: "🧑‍💻 :technologist: Improve developer experience."
              id: "🧑‍💻"
            - label: "💸 :money_with_wings: Add sponsorships or money related infrastructure."
              id: "💸"
            - label: "🧵 :thread: Add or update code related to multithreading or concurrency."
              id: "🧵"
            - label: "🦺 :safety_vest: Add or update code related to validation."
              id: "🦺"
            - label: "✈️ :airplane: Improve offline support."
              id: "✈️"
            - label: "🦖 :t-rex: Code that adds backwards compatibility."
              id: "🦖"
