# German Words

matches:

  - trigger: ":o"
    replace: "ö"
  - trigger: ":O"
    replace: "Ö"
  - trigger: ":a"
    replace: "ä"
  - trigger: ":A"
    replace: "Ä"
  - trigger: ":u"
    replace: "ü"
  - trigger: ":U"
    replace: "Ü"
  - trigger: ":Good morning"
    replace: "Guten Morgen"
  - trigger: ":How are you?"
    replace: "Wie geht es dir?"
  - trigger: ":Thank you"
    replace: "Dankeschön"
  - trigger: ":Bye"
    replace: "Tschüss"
  - trigger: ":Hi"
    replace: "Hallo"
  - trigger: ":See you next time"
    replace: "Aufwiedersehen"
  - trigger: ":the1"
    replace: "Der"
  - trigger: ":the2"
    replace: "Die"
  - trigger: ":the3"
    replace: "Das"
  - trigger: ":yes"
    replace: "Ja"
  - trigger: ":no"
    replace: "Nein"
  - trigger: ":but"
    replace: "Aber"
  - trigger: ":only"
    replace: "Nur"
  - trigger: ":on"
    replace: "An"
  - trigger: ":close"
    replace: "Zu"
  - trigger: ":from"
    replace: "Von"
  - trigger: ":S"
    replace: "ß"
  - trigger: ":apple"
    replace: "Apfel"
  - trigger: ":house"
    replace: "Haus"
  - trigger: ":dog"
    replace: "Hund"
  - trigger: ":book"
    replace: "Buch"
  - trigger: ":computer"
    replace: "Computer"
  - trigger: ":hello"
    replace: "hallo"
  - trigger: ":world"
    replace: "welt"
  - trigger: ":cat"
    replace: "katze"
  - trigger: ":dog"
    replace: "hund"
  - trigger: ":house"
    replace: "haus"
  - trigger: ":car"
    replace: "auto"
  - trigger: ":tree"
    replace: "baum"
  - trigger: ":book"
    replace: "buch"
  - trigger: ":sun"
    replace: "sonne"
  - trigger: ":moon"
    replace: "mond"
  - trigger: ":star"
    replace: "stern"
  - trigger: ":cloud"
    replace: "wolke"
  - trigger: ":rain"
    replace: "regen"
  - trigger: ":wind"
    replace: "wind"
  - trigger: ":water"
    replace: "wasser"
  - trigger: ":fire"
    replace: "feuer"
  - trigger: ":earth"
    replace: "erde"
  - trigger: ":mountain"
    replace: "berg"
  - trigger: ":river"
    replace: "fluss"
  - trigger: ":ocean"
    replace: "ozean"
  - trigger: ":friend"
    replace: "freund"
  - trigger: ":family"
    replace: "familie"
  - trigger: ":school"
    replace: "schule"
  - trigger: ":teacher"
    replace: "lehrer"
  - trigger: ":student"
    replace: "schüler"
  - trigger: ":computer"
    replace: "computer"
  - trigger: ":phone"
    replace: "telefon"
  - trigger: ":food"
    replace: "essen"
  - trigger: ":drink"
    replace: "getränk"
  - trigger: ":music"
    replace: "musik"
  - trigger: ":movie"
    replace: "film"
  - trigger: ":game"
    replace: "spiel"
  - trigger: ":work"
    replace: "arbeit"
  - trigger: ":play"
    replace: "spielen"
  - trigger: ":walk"
    replace: "gehen"
  - trigger: ":run"
    replace: "laufen"
  - trigger: ":jump"
    replace: "springen"
  - trigger: ":fly"
    replace: "fliegen"
  - trigger: ":swim"
    replace: "schwimmen"
  - trigger: ":read"
    replace: "lesen"
  - trigger: ":write"
    replace: "schreiben"
  - trigger: ":sing"
    replace: "singen"
  - trigger: ":dance"
    replace: "tanzen"
  - trigger: ":love"
    replace: "liebe"
  - trigger: ":happy"
    replace: "glücklich"
  - trigger: ":sad"
    replace: "traurig"
  - trigger: ":angry"
    replace: "wütend"
  - trigger: ":surprised"
    replace: "überrascht"
  - trigger: ":scared"
    replace: "ängstlich"
  - trigger: ":tired"
    replace: "müde"
  - trigger: ":hungry"
    replace: "hungrig"
  - trigger: ":thirsty"
    replace: "durstig"
  - trigger: ":cold"
    replace: "kalt"
  - trigger: ":hot"
    replace: "heiß"
  - trigger: ":clean"
    replace: "sauber"
  - trigger: ":dirty"
    replace: "dreckig"
  - trigger: ":strong"
    replace: "stark"
  - trigger: ":weak"
    replace: "schwach"
  - trigger: ":fast"
    replace: "schnell"
  - trigger: ":slow"
    replace: "langsam"
  - trigger: ":big"
    replace: "groß"
  - trigger: ":small"
    replace: "klein"
  - trigger: ":new"
    replace: "neu"
  - trigger: ":old"
    replace: "alt"
  - trigger: ":young"
    replace: "jung"
  - trigger: ":beautiful"
    replace: "schön"
  - trigger: ":ugly"
    replace: "hässlich"
  - trigger: ":rich"
    replace: "reich"
  - trigger: ":poor"
    replace: "arm"
  - trigger: ":easy"
    replace: "einfach"
  - trigger: ":hard"
    replace: "schwer"
  - trigger: ":open"
    replace: "offen"
  - trigger: ":closed"
    replace: "geschlossen"
  - trigger: ":early"
    replace: "früh"
  - trigger: ":late"
    replace: "spät"
  - trigger: ":light"
    replace: "licht"
  - trigger: ":dark"
    replace: "dunkel"
  - trigger: ":day"
    replace: "tag"
  - trigger: ":night"
    replace: "nacht"
  - trigger: ":garden"
    replace: "garten"
  - trigger: ":flower"
    replace: "blume"
  - trigger: ":bird"
    replace: "vogel"
  - trigger: ":fish"
    replace: "fisch"
  - trigger: ":bridge"
    replace: "brücke"
  - trigger: ":road"
    replace: "straße"
  - trigger: ":door"
    replace: "tür"
  - trigger: ":window"
    replace: "fenster"
  - trigger: ":chair"
    replace: "stuhl"
  - trigger: ":table"
    replace: "tisch"
  - trigger: ":knife"
    replace: "messer"
  - trigger: ":fork"
    replace: "gabel"
  - trigger: ":spoon"
    replace: "löffel"
  - trigger: ":plate"
    replace: "teller"
  - trigger: ":cup"
    replace: "tasse"
  - trigger: ":clock"
    replace: "uhr"
  - trigger: ":wall"
    replace: "wand"
  - trigger: ":floor"
    replace: "boden"
  - trigger: ":ceiling"
    replace: "decke"
  - trigger: ":bottle"
    replace: "flasche"
  - trigger: ":bag"
    replace: "tasche"
  - trigger: ":box"
    replace: "kiste"
  - trigger: ":lamp"
    replace: "lampe"
  - trigger: ":key"
    replace: "schlüssel"
  - trigger: ":pencil"
    replace: "bleistift"
  - trigger: ":pen"
    replace: "stift"
  - trigger: ":paper"
    replace: "papier"
  - trigger: ":note"
    replace: "notiz"
  - trigger: ":letter"
    replace: "brief"
  - trigger: ":package"
    replace: "paket"
  - trigger: ":city"
    replace: "stadt"
  - trigger: ":village"
    replace: "dorf"
  - trigger: ":forest"
    replace: "wald"
  - trigger: ":desert"
    replace: "wüste"
  - trigger: ":island"
    replace: "insel"
  - trigger: ":castle"
    replace: "schloss"
  - trigger: ":church"
    replace: "kirche"
  - trigger: ":plane"
    replace: "flugzeug"
  - trigger: ":train"
    replace: "zug"
  - trigger: ":bicycle"
    replace: "fahrrad"
  - trigger: ":boat"
    replace: "boot"
  - trigger: ":airport"
    replace: "flughafen"
  - trigger: ":station"
    replace: "bahnhof"
  - trigger: ":market"
    replace: "markt"
  - trigger: ":shop"
    replace: "geschäft"
  - trigger: ":restaurant"
    replace: "restaurant"
  - trigger: ":cafe"
    replace: "café"
  - trigger: ":park"
    replace: "park"
  - trigger: ":hospital"
    replace: "krankenhaus"
  - trigger: ":doctor"
    replace: "arzt"
  - trigger: ":nurse"
    replace: "krankenschwester"
  - trigger: ":medicine"
    replace: "medizin"
  - trigger: ":library"
    replace: "bibliothek"
  - trigger: ":museum"
    replace: "museum"
  - trigger: ":theater"
    replace: "theater"
  - trigger: ":cinema"
    replace: "kino"
  - trigger: ":hotel"
    replace: "hotel"
  - trigger: ":room"
    replace: "zimmer"
  - trigger: ":bed"
    replace: "bett"
  - trigger: ":sofa"
    replace: "sofa"
  - trigger: ":television"
    replace: "fernseher"
  - trigger: ":radio"
    replace: "radio"
  - trigger: ":camera"
    replace: "kamera"
  - trigger: ":picture"
    replace: "bild"
  - trigger: ":photograph"
    replace: "fotografie"
  - trigger: ":battery"
    replace: "batterie"
  - trigger: ":phonecall"
    replace: "anruf"
  - trigger: ":message"
    replace: "nachricht"
  - trigger: ":email"
    replace: "email"
  - trigger: ":internet"
    replace: "internet"
  - trigger: ":website"
    replace: "webseite"
  - trigger: ":software"
    replace: "software"
  - trigger: ":hardware"
    replace: "hardware"
  - trigger: ":screen"
    replace: "bildschirm"
  - trigger: ":keyboard"
    replace: "tastatur"
  - trigger: ":mouse"
    replace: "maus"
  - trigger: ":printer"
    replace: "drucker"
  - trigger: ":scanner"
    replace: "scanner"
  - trigger: ":file"
    replace: "datei"
  - trigger: ":folder"
    replace: "ordner"
  - trigger: ":document"
    replace: "dokument"
  - trigger: ":text"
    replace: "text"
  - trigger: ":title"
    replace: "titel"
  - trigger: ":name"
    replace: "name"
  - trigger: ":address"
    replace: "adresse"
  - trigger: ":country"
    replace: "land"
  - trigger: ":cityname"
    replace: "stadtname"
  - trigger: ":number"
    replace: "nummer"
  - trigger: ":date"
    replace: "datum"
  - trigger: ":time"
    replace: "zeit"
  - trigger: ":clocktime"
    replace: "uhrzeit"
  - trigger: ":minute"
    replace: "minute"
  - trigger: ":second"
    replace: "sekunde"
  - trigger: ":hour"
    replace: "stunde"
  - trigger: ":week"
    replace: "woche"
  - trigger: ":month"
    replace: "monat"
  - trigger: ":year"
    replace: "jahr"
  - trigger: ":century"
    replace: "jahrhundert"
  - trigger: ":millennium"
    replace: "jahrtausend"
  - trigger: ":weather"
    replace: "wetter"
  - trigger: ":climate"
    replace: "klima"
  - trigger: ":temperature"
    replace: "temperatur"
  - trigger: ":degree"
    replace: "grad"
  - trigger: ":storm"
    replace: "sturm"
  - trigger: ":lightning"
    replace: "blitz"
  - trigger: ":thunder"
    replace: "donner"
  - trigger: ":snow"
    replace: "schnee"
  - trigger: ":ice"
    replace: "eis"
  - trigger: ":freeze"
    replace: "frost"
  - trigger: ":warm"
    replace: "warm"
  - trigger: ":cool"
    replace: "kühl"
  - trigger: ":hotweather"
    replace: "heißeswetter"
  - trigger: ":coldweather"
    replace: "kalteswetter"
  - trigger: ":holiday"
    replace: "urlaub"
  - trigger: ":vacation"
    replace: "ferien"
  - trigger: ":travel"
    replace: "reisen"
  - trigger: ":journey"
    replace: "reise"
  - trigger: ":flight"
    replace: "flug"
  - trigger: ":ticket"
    replace: "ticket"
  - trigger: ":passport"
    replace: "pass"
  - trigger: ":visa"
    replace: "visum"
  - trigger: ":bagage"
    replace: "gepäck"
  - trigger: ":suitcase"
    replace: "koffer"
  - trigger: ":map"
    replace: "karte"
  - trigger: ":destination"
    replace: "ziel"
  - trigger: ":arrival"
    replace: "ankunft"
  - trigger: ":departure"
    replace: "abfahrt"
  - trigger: ":schedule"
    replace: "zeitplan"
  - trigger: ":bus"
    replace: "bus"
  - trigger: ":tram"
    replace: "straßenbahn"
  - trigger: ":taxi"
    replace: "taxi"
  - trigger: ":ship"
    replace: "schiff"
  - trigger: ":harbor"
    replace: "hafen"
  - trigger: ":isle"
    replace: "insel"
  - trigger: ":landscape"
    replace: "landschaft"
  - trigger: ":countryside"
    replace: "ländlich"
  - trigger: ":villagepath"
    replace: "dorfgasse"
  - trigger: ":field"
    replace: "feld"
  - trigger: ":farm"
    replace: "bauernhof"
  - trigger: ":barn"
    replace: "scheune"
  - trigger: ":crop"
    replace: "ernte"
  - trigger: ":wheat"
    replace: "weizen"
  - trigger: ":corn"
    replace: "mais"
  - trigger: ":potato"
    replace: "kartoffel"
  - trigger: ":fruit"
    replace: "obst"
  - trigger: ":vegetable"
    replace: "gemüse"
  - trigger: ":cow"
    replace: "kuh"
  - trigger: ":pig"
    replace: "schwein"
  - trigger: ":chicken"
    replace: "huhn"
  - trigger: ":duck"
    replace: "ente"
  - trigger: ":goose"
    replace: "gans"
  - trigger: ":sheep"
    replace: "schaf"
  - trigger: ":horse"
    replace: "pferd"
  - trigger: ":stable"
    replace: "stall"
  - trigger: ":milk"
    replace: "milch"
  - trigger: ":cheese"
    replace: "käse"
  - trigger: ":bread"
    replace: "brot"
  - trigger: ":meat"
    replace: "fleisch"
  - trigger: ":egg"
    replace: "ei"
  - trigger: ":soup"
    replace: "suppe"
  - trigger: ":salad"
    replace: "salat"
  - trigger: ":fruitjuice"
    replace: "fruchtsaft"
  - trigger: ":chocolate"
    replace: "schokolade"
  - trigger: ":cookie"
    replace: "keks"
  - trigger: ":cake"
    replace: "kuchen"
  - trigger: ":pie"
    replace: "torte"
  - trigger: ":icecream"
    replace: "eis"