matches:
  - trigger: ":1/4"
    replace: "¼"
  - trigger: ":1/2"
    replace: "½"
  - trigger: ":3/4"
    replace: "¾"
  - trigger: ":1/7"
    replace: "⅐"
  - trigger: ":1/9"
    replace: "⅑"
  - trigger: ":1/10"
    replace: "⅒"
  - trigger: ":1/3"
    replace: "⅓"
  - trigger: ":2/3"
    replace: "⅔"
  - trigger: ":1/5"
    replace: "⅕"
  - trigger: ":2/5"
    replace: "⅖"
  - trigger: ":3/5"
    replace: "⅗"
  - trigger: ":4/5"
    replace: "⅘"
  - trigger: ":1/6"
    replace: "⅙"
  - trigger: ":5/6"
    replace: "⅚"
  - trigger: ":1/8"
    replace: "⅛"
  - trigger: ":3/8"
    replace: "⅜"
  - trigger: ":5/8"
    replace: "⅝"
  - trigger: ":7/8"
    replace: "⅞"
