# Portuguese Accents

matches:
  - trigger: "a["
    replace: "á"
  - trigger: "A["
    replace: "Á"
  - trigger: "a{"
    replace: "à"
  - trigger: "A{"
    replace: "À"
  - trigger: "a\""
    replace: "â"
  - trigger: "A\""
    replace: "Â"
  - trigger: "a'"
    replace: "ã"
  - trigger: "A'"
    replace: "Ã"

  - trigger: "e["
    replace: "é"
  - trigger: "E["
    replace: "É"
  - trigger: "e{"
    replace: "è"
  - trigger: "E{"
    replace: "È"
  - trigger: "e\""
    replace: "ê"
  - trigger: "E\""
    replace: "Ê"

  - trigger: "i["
    replace: "í"
  - trigger: "I["
    replace: "Í"
  - trigger: "i{"
    replace: "ì"
  - trigger: "I{"
    replace: "Ì"
  - trigger: "i\""
    replace: "î"
  - trigger: "I\""
    replace: "Î"

  - trigger: "o["
    replace: "ó"
  - trigger: "O["
    replace: "Ó"
  - trigger: "o{"
    replace: "ò"
  - trigger: "O{"
    replace: "Ò"
  - trigger: "o\""
    replace: "ô"
  - trigger: "O\""
    replace: "Ô"
  - trigger: "o'"
    replace: "õ"
  - trigger: "O'"
    replace: "Õ"

  - trigger: "u["
    replace: "ú"
  - trigger: "U["
    replace: "Ú"
  - trigger: "u{"
    replace: "ù"
  - trigger: "U{"
    replace: "Ù"
  - trigger: "u\""
    replace: "û"
  - trigger: "U\""
    replace: "Û"

  - trigger: "c'"
    replace: "ç"
  - trigger: "C'"
    replace: "Ç"
