# original code from https://github.com/secwang/espanso-apl-keyboard
matches:
  - trigger: "`["
    replace: "←"
  - trigger: "`-"
    replace: "×"
  - trigger: "`="
    replace: "÷"
  - trigger: "`*"
    replace: "⍟"
  - trigger: "`+"
    replace: "⌹"
  - trigger: "`o"
    replace: "○"
  - trigger: "`s"
    replace: "⌈"
  - trigger: "`d"
    replace: "⌊"
  - trigger: "`b"
    replace: "⊥"
  - trigger: "`n"
    replace: "⊤"
  - trigger: "`|"
    replace: "⊣"
  - trigger: "`\\"
    replace: "⊢"
  - trigger: "`8"
    replace: "≠"
  - trigger: "`4"
    replace: "≤"
  - trigger: "`6"
    replace: "≥"
  - trigger: "`:"
    replace: "≡"
  - trigger: "`\""
    replace: "≢"
  - trigger: "`9"
    replace: "∨"
  - trigger: "`0"
    replace: "∧"
  - trigger: "`)"
    replace: "⍲"
  - trigger: "`("
    replace: "⍱"
  - trigger: "`y"
    replace: "↑"
  - trigger: "`u"
    replace: "↓"
  - trigger: "`z"
    replace: "⊂"
  - trigger: "`x"
    replace: "⊃"
  - trigger: "`Z"
    replace: "⊆"
  - trigger: "`L"
    replace: "⌷"
  - trigger: "`$"
    replace: "⍋"
  - trigger: "`#"
    replace: "⍒"
  - trigger: "`i"
    replace: "⍳"
  - trigger: "`I"
    replace: "⍸"
  - trigger: "`e"
    replace: "∊"
  - trigger: "`E"
    replace: "⍷"
  - trigger: "`v"
    replace: "∪"
  - trigger: "`c"
    replace: "∩"
  - trigger: "`/"
    replace: "⌿"
  - trigger: "`."
    replace: "⍀"
  - trigger: "`r"
    replace: "⍴"
  - trigger: "`%"
    replace: "⌽"
  - trigger: "`&"
    replace: "⊖"
  - trigger: "`^"
    replace: "⍉"
  - trigger: "`1"
    replace: "¨"
  - trigger: "`T"
    replace: "⍨"
  - trigger: "`P"
    replace: "⍣"
  - trigger: "`j"
    replace: "∘"
  - trigger: "`J"
    replace: "⍤"
  - trigger: "`O"
    replace: "⍥"
  - trigger: "`{"
    replace: "⍞"
  - trigger: "`l"
    replace: "⎕"
  - trigger: "`?"
    replace: "⍠"
  - trigger: "`K"
    replace: "⌸"
  - trigger: "`~"
    replace: "⌺"
  - trigger: "`!"
    replace: "⌶"
  - trigger: "`;"
    replace: "⍎"
  - trigger: "`'"
    replace: "⍕"
  - trigger: "```"
    replace: "⋄"
  - trigger: "`,"
    replace: "⍝"
  - trigger: "`]"
    replace: "→"
  - trigger: "`w"
    replace: "⍵"
  - trigger: "`a"
    replace: "⍺"
  - trigger: "`g"
    replace: "∇"
  - trigger: "`2"
    replace: "¯"
  - trigger: "`}"
    replace: "⍬"