# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json

matches:

  - trigger: ";(r);"
    replace: "®"
  - trigger: ";reg;"
    replace: "®"
  - trigger: ";(c);"
    replace: "©"
  - trigger: ";copy;"
    replace: "©"
  - trigger: ";(p);"
    replace: "℗"
  - trigger: ";tm;"
    replace: "™"
  - trigger: ";sm;"
    replace: "℠"
  - trigger: ";trade;"
    replace: "™"
  - trigger: ";deg;"
    replace: "°"
  - trigger: ";cent;"
    replace: "¢"
  - trigger: ";euro;"
    replace: "€"
  - trigger: ";times;"
    replace: "×"
  - trigger: ";divide;"
    replace: "÷"
  - trigger: ";lsq;"
    replace: "‘"
  - trigger: ";lsquo;"
    replace: "‘"
  - trigger: ";rsq;"
    replace: "’"
  - trigger: ";rsquo;"
    replace: "’"
  - trigger: ";ldq;"
    replace: "“"
  - trigger: ";ldquo;"
    replace: "“"
  - trigger: ";rdq;"
    replace: "”"
  - trigger: ";rdquo;"
    replace: "”"
  - trigger: ";ndash;"
    replace: "–"
  - trigger: ";mdash;"
    replace: "—"
  - trigger: ";nbsp;"
    replace: " "
  - trigger: ";hellip;"
    replace: "…"
  - trigger: ";bull;"
    replace: "•"
