# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json
name: common-web-chars
parent: default

matches:

  - triggers: [";(r);",";reg;"]
    replace: "®"
  - triggers: [";(c);",";copy;"]
    replace: "©"
  - triggers: [";(p);",";copysr;"]
    replace: "℗"
  - trigger: ";(m);"
    replace: "Ⓜ"
  - trigger: ";(wz);"
    replace: "🄮"
  - triggers: [";tm;",";trade;"]
    replace: "™"
  - trigger: ";sm;"
    replace: "℠"
  - trigger: ";mc;"
    replace: "🅪"
  - trigger: ";deg;"
    replace: "°"
  - trigger: ";cent;"
    replace: "¢"
  - trigger: ";euro;"
    replace: "€"
  - trigger: ";yen;"
    replace: "¥"
  - trigger: ";times;"
    replace: "×"
  - trigger: ";divide;"
    replace: "÷"
  - trigger: ";plusmn;"
    replace: "±"
  - triggers: [";lsq;",";lsquo;"]
    replace: "‘"
  - triggers: [";rsq;",";rsquo;"]
    replace: "’"
  - triggers: [";ldq;",";ldquo;"]
    replace: "“"
  - triggers: [";rdq;",";rdquo;"]
    replace: "”"
  - triggers: [";laq;",";laquo;"]
    replace: "«"
  - triggers: [";raq;",";raquo;"]
    replace: "»"
  - triggers: [";lsaq;",";lsaquo;"]
    replace: "‹"
  - triggers: [";rsaq;",";rsaquo;"]
    replace: "›"
  - trigger: ";shy;"
    replace: "\u00ad"
  - trigger: ";ndash;"
    replace: "–"
  - trigger: ";mdash;"
    replace: "—"
  - trigger: ";horbar;"
    replace: "―"
  - trigger: ";nbsp;"
    replace: "\u00a0"
  - trigger: ";hellip;"
    replace: "…"
  - trigger: ";bull;"
    replace: "•"
  - trigger: ";iexcl;"
    replace: "¡"
  - trigger: ";iquest;"
    replace: "¿"
  - trigger: ";sect;"
    replace: "§"
  - trigger: ";para;"
    replace: "¶"
  - trigger: ";dagger;"
    replace: "†"
  - trigger: ";ddagger;"
    replace: "‡"
  - trigger: ";replace;"
    replace: "\ufffd"
# White-space
  - trigger: ";ensp;"
    replace: "\u2002"
  - trigger: ";emsp;"
    replace: "\u2003"
  - trigger: ";emsp13;"
    replace: "\u2004"
  - trigger: ";emsp14;"
    replace: "\u2005"
  - trigger: ";numsp;"
    replace: "\u2007"
  - trigger: ";puncsp;"
    replace: "\u2008"
  - trigger: ";thinsp;"
    replace: "\u2009"
  - trigger: ";hairsp;"
    replace: "\u200A"
  - triggers: [";ZeroWidthSpace;",";zws;"]
    replace: "\u200B"
  - trigger: ";zwnj;"
    replace: "\u200C"
  - trigger: ";zwj;"
    replace: "\u200D"
  - trigger: ";MediumSpace;"
    replace: "\u205F"
  - trigger: ";ThickSpace;"
    replace: "\u205F\u200A"
  - triggers: [";NoBreak;",";nobr;"]
    replace: "\u2060"
# Latin-1 Supplement letters/others
  - trigger: ";curren;"
    replace: "¤"
  - trigger: ";brvbar;"
    replace: "¦"
  - trigger: ";uml;"
    replace: "¨"
  - trigger: ";ordf;"
    replace: "ª"
  - trigger: ";not;"
    replace: "¬"
  - trigger: ";macr;"
    replace: "¯"
  - trigger: ";sup2;"
    replace: "²"
  - trigger: ";sup3;"
    replace: "³"
  - trigger: ";acute;"
    replace: "´"
  - trigger: ";micro;"
    replace: "µ"
  - trigger: ";middot;"
    replace: "·"
  - trigger: ";cedil;"
    replace: "¸"
  - trigger: ";sup1;"
    replace: "¹"
  - trigger: ";ordm;"
    replace: "º"
  - trigger: ";frac14;"
    replace: "¼"
  - trigger: ";frac12;"
    replace: "½"
  - trigger: ";frac34;"
    replace: "¾"
  - trigger: ";Agrave;"
    replace: "À"
  - trigger: ";Aacute;"
    replace: "Á"
  - trigger: ";Acirc;"
    replace: "Â"
  - trigger: ";Atilde;"
    replace: "Ã"
  - trigger: ";Auml;"
    replace: "Ä"
  - trigger: ";Aring;"
    replace: "Å"
  - trigger: ";AElig;"
    replace: "Æ"
  - trigger: ";Ccedil;"
    replace: "Ç"
  - trigger: ";Egrave;"
    replace: "È"
  - trigger: ";Eacute;"
    replace: "É"
  - trigger: ";Ecirc;"
    replace: "Ê"
  - trigger: ";Euml;"
    replace: "Ë"
  - trigger: ";Igrave;"
    replace: "Ì"
  - trigger: ";Iacute;"
    replace: "Í"
  - trigger: ";Icirc;"
    replace: "Î"
  - trigger: ";Iuml;"
    replace: "Ï"
  - trigger: ";ETH;"
    replace: "Ð"
  - trigger: ";Ntilde;"
    replace: "Ñ"
  - trigger: ";Ograve;"
    replace: "Ò"
  - trigger: ";Oacute;"
    replace: "Ó"
  - trigger: ";Ocirc;"
    replace: "Ô"
  - trigger: ";Otilde;"
    replace: "Õ"
  - trigger: ";Ouml;"
    replace: "Ö"
  - trigger: ";Oslash;"
    replace: "Ø"
  - trigger: ";Ugrave;"
    replace: "Ù"
  - trigger: ";Uacute;"
    replace: "Ú"
  - trigger: ";Ucirc;"
    replace: "Û"
  - trigger: ";Uuml;"
    replace: "Ü"
  - trigger: ";Yacute;"
    replace: "Ý"
  - trigger: ";THORN;"
    replace: "Þ"
  - trigger: ";szlig;"
    replace: "ß"
  - trigger: ";agrave;"
    replace: "à"
  - trigger: ";aacute;"
    replace: "á"
  - trigger: ";acirc;"
    replace: "â"
  - trigger: ";atilde;"
    replace: "ã"
  - trigger: ";auml;"
    replace: "ä"
  - trigger: ";aring;"
    replace: "å"
  - trigger: ";aelig;"
    replace: "æ"
  - trigger: ";ccedil;"
    replace: "ç"
  - trigger: ";egrave;"
    replace: "è"
  - trigger: ";eacute;"
    replace: "é"
  - trigger: ";ecirc;"
    replace: "ê"
  - trigger: ";euml;"
    replace: "ë"
  - trigger: ";igrave;"
    replace: "ì"
  - trigger: ";iacute;"
    replace: "í"
  - trigger: ";icirc;"
    replace: "î"
  - trigger: ";iuml;"
    replace: "ï"
  - trigger: ";eth;"
    replace: "ð"
  - trigger: ";ntilde;"
    replace: "ñ"
  - trigger: ";ograve;"
    replace: "ò"
  - trigger: ";oacute;"
    replace: "ó"
  - trigger: ";ocirc;"
    replace: "ô"
  - trigger: ";otilde;"
    replace: "õ"
  - trigger: ";ouml;"
    replace: "ö"
  - trigger: ";oslash;"
    replace: "ø"
  - trigger: ";ugrave;"
    replace: "ù"
  - trigger: ";uacute;"
    replace: "ú"
  - trigger: ";ucirc;"
    replace: "û"
  - trigger: ";uuml;"
    replace: "ü"
  - trigger: ";yacute;"
    replace: "ý"
  - trigger: ";thorn;"
    replace: "þ"
  - trigger: ";yuml;"
    replace: "ÿ"
# Latin Extended-A
  - trigger: ";Amacr;"
    replace: "Ā"
  - trigger: ";amacr;"
    replace: "ā"
  - trigger: ";Abreve;"
    replace: "Ă"
  - trigger: ";abreve;"
    replace: "ă"
  - trigger: ";Aogon;"
    replace: "Ą"
  - trigger: ";aogon;"
    replace: "ą"
  - trigger: ";Cacute;"
    replace: "Ć"
  - trigger: ";cacute;"
    replace: "ć"
  - trigger: ";Ccirc;"
    replace: "Ĉ"
  - trigger: ";ccirc;"
    replace: "ĉ"
  - trigger: ";Cdot;"
    replace: "Ċ"
  - trigger: ";cdot;"
    replace: "ċ"
  - trigger: ";Ccaron;"
    replace: "Č"
  - trigger: ";ccaron;"
    replace: "č"
  - trigger: ";Dcaron;"
    replace: "Ď"
  - trigger: ";dcaron;"
    replace: "ď"
  - trigger: ";Dstrok;"
    replace: "Đ"
  - trigger: ";dstrok;"
    replace: "đ"
  - trigger: ";Emacr;"
    replace: "Ē"
  - trigger: ";emacr;"
    replace: "ē"
  - trigger: ";Ebreve;"
    replace: "Ĕ"
  - trigger: ";ebreve;"
    replace: "ĕ"
  - trigger: ";Edot;"
    replace: "Ė"
  - trigger: ";edot;"
    replace: "ė"
  - trigger: ";Eogon;"
    replace: "Ę"
  - trigger: ";eogon;"
    replace: "ę"
  - trigger: ";Ecaron;"
    replace: "Ě"
  - trigger: ";ecaron;"
    replace: "ě"
  - trigger: ";Gcirc;"
    replace: "Ĝ"
  - trigger: ";gcirc;"
    replace: "ĝ"
  - trigger: ";Gbreve;"
    replace: "Ğ"
  - trigger: ";gbreve;"
    replace: "ğ"
  - trigger: ";Gdot;"
    replace: "Ġ"
  - trigger: ";gdot;"
    replace: "ġ"
  - trigger: ";Gcedil;"
    replace: "Ģ"
  - trigger: ";gcedil;"
    replace: "ģ"
  - trigger: ";Hcirc;"
    replace: "Ĥ"
  - trigger: ";hcirc;"
    replace: "ĥ"
  - trigger: ";Hstrok;"
    replace: "Ħ"
  - trigger: ";hstrok;"
    replace: "ħ"
  - trigger: ";Itilde;"
    replace: "Ĩ"
  - trigger: ";itilde;"
    replace: "ĩ"
  - trigger: ";Imacr;"
    replace: "Ī"
  - trigger: ";imacr;"
    replace: "ī"
  - trigger: ";Ibreve;"
    replace: "Ĭ"
  - trigger: ";ibreve;"
    replace: "ĭ"
  - trigger: ";Iogon;"
    replace: "Į"
  - trigger: ";iogon;"
    replace: "į"
  - trigger: ";Idot;"
    replace: "İ"
  - trigger: ";inodot;"
    replace: "ı"
  - trigger: ";IJlig;"
    replace: "Ĳ"
  - trigger: ";ijlig;"
    replace: "ĳ"
  - trigger: ";Jcirc;"
    replace: "Ĵ"
  - trigger: ";jcirc;"
    replace: "ĵ"
  - trigger: ";Kcedil;"
    replace: "Ķ"
  - trigger: ";kcedil;"
    replace: "ķ"
  - trigger: ";kgreen;"
    replace: "ĸ"
  - trigger: ";Lacute;"
    replace: "Ĺ"
  - trigger: ";lacute;"
    replace: "ĺ"
  - trigger: ";Lcedil;"
    replace: "Ļ"
  - trigger: ";lcedil;"
    replace: "ļ"
  - trigger: ";Lcaron;"
    replace: "Ľ"
  - trigger: ";lcaron;"
    replace: "ľ"
  - trigger: ";Lmidot;"
    replace: "Ŀ"
  - trigger: ";lmidot;"
    replace: "ŀ"
  - trigger: ";Lstrok;"
    replace: "Ł"
  - trigger: ";lstrok;"
    replace: "ł"
  - trigger: ";Nacute;"
    replace: "Ń"
  - trigger: ";nacute;"
    replace: "ń"
  - trigger: ";Ncedil;"
    replace: "Ņ"
  - trigger: ";ncedil;"
    replace: "ņ"
  - trigger: ";Ncaron;"
    replace: "Ň"
  - trigger: ";ncaron;"
    replace: "ň"
  - trigger: ";napos;"
    replace: "ŉ"
  - trigger: ";ENG;"
    replace: "Ŋ"
  - trigger: ";eng;"
    replace: "ŋ"
  - trigger: ";Omacr;"
    replace: "Ō"
  - trigger: ";omacr;"
    replace: "ō"
  - trigger: ";Obreve;"
    replace: "Ŏ"
  - trigger: ";obreve;"
    replace: "ŏ"
  - trigger: ";Odblac;"
    replace: "Ő"
  - trigger: ";odblac;"
    replace: "ő"
  - trigger: ";OElig;"
    replace: "Œ"
  - trigger: ";oelig;"
    replace: "œ"
  - trigger: ";Racute;"
    replace: "Ŕ"
  - trigger: ";racute;"
    replace: "ŕ"
  - trigger: ";Rcedil;"
    replace: "Ŗ"
  - trigger: ";rcedil;"
    replace: "ŗ"
  - trigger: ";Rcaron;"
    replace: "Ř"
  - trigger: ";rcaron;"
    replace: "ř"
  - trigger: ";Sacute;"
    replace: "Ś"
  - trigger: ";sacute;"
    replace: "ś"
  - trigger: ";Scirc;"
    replace: "Ŝ"
  - trigger: ";scirc;"
    replace: "ŝ"
  - trigger: ";Scedil;"
    replace: "Ş"
  - trigger: ";scedil;"
    replace: "ş"
  - trigger: ";Scaron;"
    replace: "Š"
  - trigger: ";scaron;"
    replace: "š"
  - trigger: ";Tcedil;"
    replace: "Ţ"
  - trigger: ";tcedil;"
    replace: "ţ"
  - trigger: ";Tcaron;"
    replace: "Ť"
  - trigger: ";tcaron;"
    replace: "ť"
  - trigger: ";Tstrok;"
    replace: "Ŧ"
  - trigger: ";tstrok;"
    replace: "ŧ"
  - trigger: ";Utilde;"
    replace: "Ũ"
  - trigger: ";utilde;"
    replace: "ũ"
  - trigger: ";Umacr;"
    replace: "Ū"
  - trigger: ";umacr;"
    replace: "ū"
  - trigger: ";Ubreve;"
    replace: "Ŭ"
  - trigger: ";ubreve;"
    replace: "ŭ"
  - trigger: ";Uring;"
    replace: "Ů"
  - trigger: ";uring;"
    replace: "ů"
  - trigger: ";Udblac;"
    replace: "Ű"
  - trigger: ";udblac;"
    replace: "ű"
  - trigger: ";Uogon;"
    replace: "Ų"
  - trigger: ";uogon;"
    replace: "ų"
  - trigger: ";Wcirc;"
    replace: "Ŵ"
  - trigger: ";wcirc;"
    replace: "ŵ"
  - trigger: ";Ycirc;"
    replace: "Ŷ"
  - trigger: ";ycirc;"
    replace: "ŷ"
  - trigger: ";Yuml;"
    replace: "Ÿ"
  - trigger: ";Zacute;"
    replace: "Ź"
  - trigger: ";zacute;"
    replace: "ź"
  - trigger: ";Zdot;"
    replace: "Ż"
  - trigger: ";zdot;"
    replace: "ż"
  - trigger: ";Zcaron;"
    replace: "Ž"
  - trigger: ";zcaron;"
    replace: "ž"
