
matches:
  # {{{ Encircled numbers 0-50
  # https://www.webnots.com/alt-code-shortcuts-for-encircled-numbers/
  - trigger: ';o0'
    replace: '⓪'
  - trigger: ';o1'
    replace: '①'
  - trigger: ';o2'
    replace: '②'
  - trigger: ';o3'
    replace: '③'
  - trigger: ';o4'
    replace: '④'
  - trigger: ';o5'
    replace: '⑤'
  - trigger: ';o6'
    replace: '⑥'
  - trigger: ';o7'
    replace: '⑦'
  - trigger: ';o8'
    replace: '⑧'
  - trigger: ';o9'
    replace: '⑨'
  - trigger: ';o.10'
    replace: '⑩'
  - trigger: ';o.11'
    replace: '⑪'
  - trigger: ';o.12'
    replace: '⑫'
  - trigger: ';o.13'
    replace: '⑬'
  - trigger: ';o.14'
    replace: '⑭'
  - trigger: ';o.15'
    replace: '⑮'
  - trigger: ';o.16'
    replace: '⑯'
  - trigger: ';o.17'
    replace: '⑰'
  - trigger: ';o.18'
    replace: '⑱'
  - trigger: ';o.19'
    replace: '⑲'
  - trigger: ';o.20'
    replace: '⑳'
  - trigger: ';o.21'
    replace: '㉑'
  - trigger: ';o.22'
    replace: '㉒'
  - trigger: ';o.23'
    replace: '㉓'
  - trigger: ';o.24'
    replace: '㉔'
  - trigger: ';o.25'
    replace: '㉕'
  - trigger: ';o.26'
    replace: '㉖'
  - trigger: ';o.27'
    replace: '㉗'
  - trigger: ';o.28'
    replace: '㉘'
  - trigger: ';o.29'
    replace: '㉙'
  - trigger: ';o.30'
    replace: '㉚'
  - trigger: ';o.31'
    replace: '㉛'
  - trigger: ';o.32'
    replace: '㉜'
  - trigger: ';o.33'
    replace: '㉝'
  - trigger: ';o.34'
    replace: '㉞'
  - trigger: ';o.35'
    replace: '㉟'
  - trigger: ';o.36'
    replace: '㊱'
  - trigger: ';o.37'
    replace: '㊲'
  - trigger: ';o.38'
    replace: '㊳'
  - trigger: ';o.39'
    replace: '㊴'
  - trigger: ';o.40'
    replace: '㊵'
  - trigger: ';o.41'
    replace: '㊶'
  - trigger: ';o.42'
    replace: '㊷'
  - trigger: ';o.43'
    replace: '㊸'
  - trigger: ';o.44'
    replace: '㊹'
  - trigger: ';o.45'
    replace: '㊺'
  - trigger: ';o.46'
    replace: '㊻'
  - trigger: ';o.47'
    replace: '㊼'
  - trigger: ';o.48'
    replace: '㊽'
  - trigger: ';o.49'
    replace: '㊾'
  - trigger: ';o.50'
    replace: '㊿'
  # }}}

  # {{{ Negative encircled numbers 0-20
  # https://www.webnots.com/alt-code-shortcuts-for-encircled-numbers/
  - trigger: ';no0'
    replace: '⓿'
  - trigger: ';no1'
    replace: '❶'
  - trigger: ';no2'
    replace: '❷'
  - trigger: ';no3'
    replace: '❸'
  - trigger: ';no4'
    replace: '❹'
  - trigger: ';no5'
    replace: '❺'
  - trigger: ';no6'
    replace: '❻'
  - trigger: ';no7'
    replace: '❼'
  - trigger: ';no8'
    replace: '❽'
  - trigger: ';no9'
    replace: '❾'
  - trigger: ';no.10'
    replace: '❿'
  - trigger: ';no.11'
    replace: '⓫'
  - trigger: ';no.12'
    replace: '⓬'
  - trigger: ';no.13'
    replace: '⓭'
  - trigger: ';no.14'
    replace: '⓮'
  - trigger: ';no.15'
    replace: '⓯'
  - trigger: ';no.16'
    replace: '⓰'
  - trigger: ';no.17'
    replace: '⓱'
  - trigger: ';no.18'
    replace: '⓲'
  - trigger: ';no.19'
    replace: '⓳'
  - trigger: ';no.20'
    replace: '⓴'
  # }}}