name: typofixer-es
parent: default
matches:
- trigger: Carcas
  replace: Caracas
  propagate_case: true
  word: true
- trigger: abandoran
  replace: abandonar
  propagate_case: true
  word: true
- trigger: abandoanr
  replace: abandonar
  propagate_case: true
  word: true
- trigger: addios
  replace: adios
  propagate_case: true
  word: true
- trigger: adulterdo
  replace: adulterado
  propagate_case: true
  word: true
- trigger: "afirmasi\xF3n"
  replace: "afirmaci\xF3n"
  propagate_case: true
  word: true
- trigger: alunmos
  replace: alumnos
  propagate_case: true
  word: true
- trigger: amorso
  replace: amoroso
  propagate_case: true
  word: true
- trigger: aprarce
  replace: aparece
  propagate_case: true
  word: true
- trigger: avansar
  replace: avanzar
  propagate_case: true
  word: true
- trigger: "adversi\xF3n"
  replace: "aversi\xF3n"
  propagate_case: true
  word: true
- trigger: ayudrate
  replace: ayudarte
  propagate_case: true
  word: true
- trigger: vanal
  replace: banal
  propagate_case: true
  word: true
- trigger: beuno
  replace: bueno
  propagate_case: true
  word: true
- trigger: cantra
  replace: cantar
  propagate_case: true
  word: true
- trigger: capsidad
  replace: capacidad
  propagate_case: true
  word: true
- trigger: capasidad
  replace: capacidad
  propagate_case: true
  word: true
- trigger: casua
  replace: causa
  propagate_case: true
  word: true
- trigger: sepillo
  replace: cepillo
  propagate_case: true
  word: true
- trigger: cojer
  replace: coger
  propagate_case: true
  word: true
- trigger: conmenzar
  replace: comenzar
  propagate_case: true
  word: true
- trigger: conumismo
  replace: comunismo
  propagate_case: true
  word: true
- trigger: consciencia
  replace: conciencia
  propagate_case: true
  word: true
- trigger: conciensia
  replace: conciencia
  propagate_case: true
  word: true
- trigger: consiensia
  replace: conciencia
  propagate_case: true
  word: true
- trigger: consiencia
  replace: conciencia
  propagate_case: true
  word: true
- trigger: contendo
  replace: contento
  propagate_case: true
  word: true
- trigger: convalescencia
  replace: convalecencia
  propagate_case: true
  word: true
- trigger: conyontura
  replace: conyuntura
  propagate_case: true
  word: true
- trigger: ciudar
  replace: cuidar
  propagate_case: true
  word: true
- trigger: "desici\xF3n"
  replace: "decisi\xF3n"
  propagate_case: true
  word: true
- trigger: desabitado
  replace: deshabitado
  propagate_case: true
  word: true
- trigger: desecho
  replace: deshecho
  propagate_case: true
  word: true
- trigger: desdecho
  replace: deshecho
  propagate_case: true
  word: true
- trigger: depsenderse
  replace: desprenderse
  propagate_case: true
  word: true
- trigger: desprenderce
  replace: desprenderse
  propagate_case: true
  word: true
- trigger: disitintos
  replace: distintos
  propagate_case: true
  word: true
- trigger: editorail
  replace: editorial
  propagate_case: true
  word: true
- trigger: efectiviad
  replace: efectividad
  propagate_case: true
  word: true
- trigger: empiesza
  replace: empieza
  propagate_case: true
  word: true
- trigger: enfermp
  replace: enfermo
  propagate_case: true
  word: true
- trigger: enfretnarse
  replace: enfrentarse
  propagate_case: true
  word: true
- trigger: enferente
  replace: enfrente
  propagate_case: true
  word: true
- trigger: enojadp
  replace: enojado
  propagate_case: true
  word: true
- trigger: espisodios
  replace: episodios
  propagate_case: true
  word: true
- trigger: escojer
  replace: escoger
  propagate_case: true
  word: true
- trigger: "exc\xE9ptico"
  replace: "esc\xE9ptico"
  propagate_case: true
  word: true
- trigger: esperamso
  replace: esperamos
  propagate_case: true
  word: true
- trigger: estimaods
  replace: estimados
  propagate_case: true
  word: true
- trigger: estimaos
  replace: estimados
  propagate_case: true
  word: true
- trigger: estubiera
  replace: estuviera
  propagate_case: true
  word: true
- trigger: exalar
  replace: exhalar
  propagate_case: true
  word: true
- trigger: exausto
  replace: exhausto
  propagate_case: true
  word: true
- trigger: exortar
  replace: exhortar
  propagate_case: true
  word: true
- trigger: exumar
  replace: exhumar
  propagate_case: true
  word: true
- trigger: familai
  replace: familia
  propagate_case: true
  word: true
- trigger: fideligno
  replace: fidedigno
  propagate_case: true
  word: true
- trigger: frotnera
  replace: frontera
  propagate_case: true
  word: true
- trigger: garage
  replace: garaje
  propagate_case: true
  word: true
- trigger: genral
  replace: general
  propagate_case: true
  word: true
- trigger: glosairo
  replace: glosario
  propagate_case: true
  word: true
- trigger: gracas
  replace: gracias
  propagate_case: true
  word: true
- trigger: gusanso
  replace: gusano
  propagate_case: true
  word: true
- trigger: human
  replace: humano
  propagate_case: true
  word: true
- trigger: idiocincracia
  replace: idiocincrasia
  propagate_case: true
  word: true
- trigger: "iluis\xF3n"
  replace: "ilusi\xF3n"
  propagate_case: true
  word: true
- trigger: infanca
  replace: infancia
  propagate_case: true
  word: true
- trigger: inflingido
  replace: infligido
  propagate_case: true
  word: true
- trigger: insistr
  replace: insistir
  propagate_case: true
  word: true
- trigger: incistir
  replace: insistir
  propagate_case: true
  word: true
- trigger: ingerencia
  replace: injerencia
  propagate_case: true
  word: true
- trigger: interesnate
  replace: interesante
  propagate_case: true
  word: true
- trigger: interez
  replace: "inter\xE9s"
  propagate_case: true
  word: true
- trigger: llroar
  replace: llorar
  propagate_case: true
  word: true
- trigger: "mis\xF3geno"
  replace: "mis\xF3gino"
  propagate_case: true
  word: true
- trigger: meustra
  replace: muestra
  propagate_case: true
  word: true
- trigger: "m\xF3bil"
  replace: "m\xF3vil"
  propagate_case: true
  word: true
- trigger: nosotrs
  replace: nosotros
  propagate_case: true
  word: true
- trigger: novedaes
  replace: novedades
  propagate_case: true
  word: true
- trigger: neustra
  replace: nuestra
  propagate_case: true
  word: true
- trigger: neuvo
  replace: nuevo
  propagate_case: true
  word: true
- trigger: "ocaci\xF3n"
  replace: "ocasi\xF3n"
  propagate_case: true
  word: true
- trigger: holor
  replace: olor
  propagate_case: true
  word: true
- trigger: pra
  replace: para
  propagate_case: true
  word: true
- trigger: plajio
  replace: plagio
  propagate_case: true
  word: true
- trigger: preparadso
  replace: preparados
  propagate_case: true
  word: true
- trigger: "preci\xF3n"
  replace: "presi\xF3n"
  propagate_case: true
  word: true
- trigger: prsetarnos
  replace: prestarnos
  propagate_case: true
  word: true
- trigger: preveer
  replace: prever
  propagate_case: true
  word: true
- trigger: professor
  replace: profesor
  propagate_case: true
  word: true
- trigger: proihibido
  replace: prohibido
  propagate_case: true
  word: true
- trigger: proibido
  replace: prohibido
  propagate_case: true
  word: true
- trigger: puevlo
  replace: pueblo
  propagate_case: true
  word: true
- trigger: realiad
  replace: realidad
  propagate_case: true
  word: true
- trigger: relacions
  replace: relaciones
  propagate_case: true
  word: true
- trigger: relasion
  replace: relaciones
  propagate_case: true
  word: true
- trigger: resvalando
  replace: resbalando
  propagate_case: true
  word: true
- trigger: ruputura
  replace: ruptura
  propagate_case: true
  word: true
- trigger: sakapuntas
  replace: sacapuntas
  propagate_case: true
  word: true
- trigger: socail
  replace: social
  propagate_case: true
  word: true
- trigger: socieda
  replace: sociedad
  propagate_case: true
  word: true
- trigger: sosiedad
  replace: sociedad
  propagate_case: true
  word: true
- trigger: soldedad
  replace: soledad
  propagate_case: true
  word: true
- trigger: solaedad
  replace: soledad
  propagate_case: true
  word: true
- trigger: solidairo
  replace: solidario
  propagate_case: true
  word: true
- trigger: temrinaba
  replace: terminaba
  propagate_case: true
  word: true
- trigger: teinda
  replace: tienda
  propagate_case: true
  word: true
- trigger: "todab\xEDa"
  replace: "todav\xEDa"
  propagate_case: true
  word: true
- trigger: traducidso
  replace: traducidos
  propagate_case: true
  word: true
- trigger: traduciods
  replace: traducidos
  propagate_case: true
  word: true
- trigger: traspsan
  replace: traspasan
  propagate_case: true
  word: true
- trigger: traspsar
  replace: traspasar
  propagate_case: true
  word: true
- trigger: transtornado
  replace: trastornado
  propagate_case: true
  word: true
- trigger: "t\xF3xisac"
  replace: "t\xF3xicas"
  propagate_case: true
  word: true
- trigger: unidso
  replace: unidos
  propagate_case: true
  word: true
- trigger: vacasiones
  replace: vacaciones
  propagate_case: true
  word: true
- trigger: vacasions
  replace: vacaciones
  propagate_case: true
  word: true
- trigger: llendo
  replace: yendo
  propagate_case: true
  word: true
