# turkish-accent

matches:
  - trigger: ":i"
    replace: "ı"
  - trigger: ":u"
    replace: "ü"
  - trigger: ":s"
    replace: "ş"
  - trigger: ":c"
    replace: "ç"
  - trigger: ":o"
    replace: "ö"
  - trigger: ":g"
    replace: "ğ"
  - trigger: ":I"
    replace: "İ"
  - trigger: ":U"
    replace: "Ü"
  - trigger: ":S"
    replace: "Ş"
  - trigger: ":C"
    replace: "Ç"
  - trigger: ":O"
    replace: "Ö"
  - trigger: ":G"
    replace: "Ğ"
