matches:
  - trigger: ":calc"
    replace: "{{result}}"
    vars:
      - name: "input"
        type: "form"
        params:
          layout: |
            Enter expression (e.g. (19+1)^2): [[val]]
      - name: result
        type: script
        params:
          args:
            - python
            - -c
            - |
              from math import *
              x = '{{input.val}}'.replace('^', '**')
              r = eval(x)
              print(int(r) if r == int(r) else round(r, 10))

  - trigger: ":xcalc"
    replace: "{{input.val}} = {{result}}"
    vars:
      - name: "input"
        type: "form"
        params:
          layout: |
            Enter expression (e.g. (19+1)^2): [[val]]
      - name: result
        type: script
        params:
          args:
            - python
            - -c
            - |
              from math import *
              x = '{{input.val}}'.replace('^', '**')
              r = eval(x)
              print(int(r) if r == int(r) else round(r, 10))