# Apple Symbols

matches:
  - trigger: ":alt"
    replace: "⌥"

  - trigger: ":bs"
    replace: "⌫"

  - trigger: ":cmd"
    replace: "⌘"

  - trigger: ":ctrl"
    replace: "⌃"

  - trigger: ":shift"
    replace: "⇧"

  - trigger: ":tab"
    replace: "⇥"

  - trigger: ":cap"
    replace: "⇪"

  - trigger: ":eject"
    replace: "⏏︎"

  - trigger: ":esc"
    replace: "␛"
