
matches:
  # {{{ Script letters
  # https://www.webnots.com/alt-code-shortcuts-for-english-letters/
  - trigger: ';sA'
    replace: 'ğ’œ'
  - trigger: ';sB'
    replace: 'â„¬'
  - trigger: ';sC'
    replace: 'ğ’'
  - trigger: ';sD'
    replace: 'ğ’Ÿ'
  - trigger: ';sE'
    replace: 'â„°'
  - trigger: ';sF'
    replace: 'â„±'
  - trigger: ';sG'
    replace: 'ğ’¢'
  - trigger: ';sH'
    replace: 'â„‹'
  - trigger: ';sI'
    replace: 'â„'
  - trigger: ';sJ'
    replace: 'ğ’¥'
  - trigger: ';sK'
    replace: 'ğ’¦'
  - trigger: ';sL'
    replace: 'â„’'
  - trigger: ';sM'
    replace: 'â„³'
  - trigger: ';sN'
    replace: 'ğ’©'
  - trigger: ';sO'
    replace: 'ğ’ª'
  - trigger: ';sP'
    replace: 'ğ’«'
  - trigger: ';sQ'
    replace: 'ğ’¬'
  - trigger: ';sR'
    replace: 'â„›'
  - trigger: ';sS'
    replace: 'ğ’®'
  - trigger: ';sT'
    replace: 'ğ’¯'
  - trigger: ';sU'
    replace: 'ğ’°'
  - trigger: ';sV'
    replace: 'ğ’±'
  - trigger: ';sW'
    replace: 'ğ’²'
  - trigger: ';sX'
    replace: 'ğ’³'
  - trigger: ';sY'
    replace: 'ğ’´'
  - trigger: ';sZ'
    replace: 'ğ’µ'
  - trigger: ';sa'
    replace: 'ğ’¶'
  - trigger: ';sb'
    replace: 'ğ’·'
  - trigger: ';sc'
    replace: 'ğ’¸'
  - trigger: ';sd'
    replace: 'ğ’¹'
  - trigger: ';se'
    replace: 'â„¯'
  - trigger: ';sf'
    replace: 'ğ’»'
  - trigger: ';sg'
    replace: 'â„Š'
  - trigger: ';sh'
    replace: 'ğ’½'
  - trigger: ';si'
    replace: 'ğ’¾'
  - trigger: ';sj'
    replace: 'ğ’¿'
  - trigger: ';sk'
    replace: 'ğ“€'
  - trigger: ';sl'
    replace: 'ğ“'
  - trigger: ';sm'
    replace: 'ğ“‚'
  - trigger: ';sn'
    replace: 'ğ“ƒ'
  - trigger: ';so'
    replace: 'â„´'
  - trigger: ';sp'
    replace: 'ğ“…'
  - trigger: ';sq'
    replace: 'ğ“†'
  - trigger: ';sr'
    replace: 'ğ“‡'
  - trigger: ';ss'
    replace: 'ğ“ˆ'
  - trigger: ';st'
    replace: 'ğ“‰'
  - trigger: ';su'
    replace: 'ğ“Š'
  - trigger: ';sv'
    replace: 'ğ“‹'
  - trigger: ';sw'
    replace: 'ğ“Œ'
  - trigger: ';sx'
    replace: 'ğ“'
  - trigger: ';sy'
    replace: 'ğ“'
  - trigger: ';sz'
    replace: 'ğ“'
  - trigger: ';sA'
    replace: 'ğ“'
  - trigger: ';sB'
    replace: 'ğ“‘'
  - trigger: ';sC'
    replace: 'ğ“’'
  - trigger: ';sD'
    replace: 'ğ““'
  - trigger: ';sE'
    replace: 'ğ“”'
  - trigger: ';sF'
    replace: 'ğ“•'
  - trigger: ';sG'
    replace: 'ğ“–'
  - trigger: ';sH'
    replace: 'ğ“—'
  - trigger: ';sI'
    replace: 'ğ“˜'
  - trigger: ';sJ'
    replace: 'ğ“™'
  - trigger: ';sK'
    replace: 'ğ“š'
  - trigger: ';sL'
    replace: 'ğ“›'
  - trigger: ';sM'
    replace: 'ğ“œ'
  - trigger: ';sN'
    replace: 'ğ“'
  - trigger: ';sO'
    replace: 'ğ“'
  - trigger: ';sP'
    replace: 'ğ“Ÿ'
  - trigger: ';sQ'
    replace: 'ğ“ '
  - trigger: ';sR'
    replace: 'ğ“¡'
  - trigger: ';sS'
    replace: 'ğ“¢'
  - trigger: ';sT'
    replace: 'ğ“£'
  - trigger: ';sU'
    replace: 'ğ“¤'
  - trigger: ';sV'
    replace: 'ğ“¥'
  - trigger: ';sW'
    replace: 'ğ“¦'
  - trigger: ';sX'
    replace: 'ğ“§'
  - trigger: ';sY'
    replace: 'ğ“¨'
  - trigger: ';sZ'
    replace: 'ğ“©'
  - trigger: ';sa'
    replace: 'ğ“ª'
  - trigger: ';sb'
    replace: 'ğ“«'
  - trigger: ';sc'
    replace: 'ğ“¬'
  - trigger: ';sd'
    replace: 'ğ“­'
  - trigger: ';se'
    replace: 'ğ“®'
  - trigger: ';sf'
    replace: 'ğ“¯'
  - trigger: ';sg'
    replace: 'ğ“°'
  - trigger: ';sh'
    replace: 'ğ“±'
  - trigger: ';si'
    replace: 'ğ“²'
  - trigger: ';sj'
    replace: 'ğ“³'
  - trigger: ';sk'
    replace: 'ğ“´'
  - trigger: ';sl'
    replace: 'ğ“µ'
  - trigger: ';sm'
    replace: 'ğ“¶'
  - trigger: ';sn'
    replace: 'ğ“·'
  - trigger: ';so'
    replace: 'ğ“¸'
  - trigger: ';sp'
    replace: 'ğ“¹'
  - trigger: ';sq'
    replace: 'ğ“º'
  - trigger: ';sr'
    replace: 'ğ“»'
  - trigger: ';ss'
    replace: 'ğ“¼'
  - trigger: ';st'
    replace: 'ğ“½'
  - trigger: ';su'
    replace: 'ğ“¾'
  - trigger: ';sv'
    replace: 'ğ“¿'
  - trigger: ';sw'
    replace: 'ğ”€'
  - trigger: ';sx'
    replace: 'ğ”'
  - trigger: ';sy'
    replace: 'ğ”‚'
  - trigger: ';sz'
    replace: 'ğ”ƒ'
  # }}}