name: test-hub-deploy

# TODO: this workflow should be deleted!

on:
  pull_request:

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Setup SSH deploy key"
        uses: webfactory/ssh-agent@fc49353b67b2b7c1e0e6a600572d01a69f2672dd
        with:
          ssh-private-key: ${{ secrets.HUB_FRONTEND_DEPLOY_KEY }}
      - name: "Push update on hub-frontend"
        run: |
          git config --global user.name "Espanso Hub Bot"

          git clone git@github.com:espanso/hub-frontend.git
          cd hub-frontend

          git rev-parse --verify HEAD > current_hub_sha.txt
          git add current_hub_sha.txt
          git commit -m "chore(misc): auto deploy from HUB CI"
          git push