matches:
  # {{{ Encircled Letters
  # https://www.webnots.com/alt-code-shortcuts-for-circled-letters/
  - trigger: ';oA'
    replace: 'Ⓐ'
  - trigger: ';oB'
    replace: 'Ⓑ'
  - trigger: ';oC'
    replace: 'Ⓒ'
  - trigger: ';oD'
    replace: 'Ⓓ'
  - trigger: ';oE'
    replace: 'Ⓔ'
  - trigger: ';oF'
    replace: 'Ⓕ'
  - trigger: ';oG'
    replace: 'Ⓖ'
  - trigger: ';oH'
    replace: 'Ⓗ'
  - trigger: ';oI'
    replace: 'Ⓘ'
  - trigger: ';oJ'
    replace: 'Ⓙ'
  - trigger: ';oK'
    replace: 'Ⓚ'
  - trigger: ';oL'
    replace: 'Ⓛ'
  - trigger: ';oM'
    replace: 'Ⓜ'
  - trigger: ';oN'
    replace: 'Ⓝ'
  - trigger: ';oO'
    replace: 'Ⓞ'
  - trigger: ';oP'
    replace: 'Ⓟ'
  - trigger: ';oQ'
    replace: 'Ⓠ'
  - trigger: ';oR'
    replace: 'Ⓡ'
  - trigger: ';oS'
    replace: 'Ⓢ'
  - trigger: ';oT'
    replace: 'Ⓣ'
  - trigger: ';oU'
    replace: 'Ⓤ'
  - trigger: ';oV'
    replace: 'Ⓥ'
  - trigger: ';oW'
    replace: 'Ⓦ'
  - trigger: ';oX'
    replace: 'Ⓧ'
  - trigger: ';oY'
    replace: 'Ⓨ'
  - trigger: ';oZ'
    replace: 'Ⓩ'
  - trigger: ';oa'
    replace: 'ⓐ'
  - trigger: ';ob'
    replace: 'ⓑ'
  - trigger: ';oc'
    replace: 'ⓒ'
  - trigger: ';od'
    replace: 'ⓓ'
  - trigger: ';oe'
    replace: 'ⓔ'
  - trigger: ';of'
    replace: 'ⓕ'
  - trigger: ';og'
    replace: 'ⓖ'
  - trigger: ';oh'
    replace: 'ⓗ'
  - trigger: ';oi'
    replace: 'ⓘ'
  - trigger: ';oj'
    replace: 'ⓙ'
  - trigger: ';ok'
    replace: 'ⓚ'
  - trigger: ';ol'
    replace: 'ⓛ'
  - trigger: ';om'
    replace: 'ⓜ'
  - trigger: ';on'
    replace: 'ⓝ'
  - trigger: ';oo'
    replace: 'ⓞ'
  - trigger: ';op'
    replace: 'ⓟ'
  - trigger: ';oq'
    replace: 'ⓠ'
  - trigger: ';or'
    replace: 'ⓡ'
  - trigger: ';os'
    replace: 'ⓢ'
  - trigger: ';ot'
    replace: 'ⓣ'
  - trigger: ';ou'
    replace: 'ⓤ'
  - trigger: ';ov'
    replace: 'ⓥ'
  - trigger: ';ow'
    replace: 'ⓦ'
  - trigger: ';ox'
    replace: 'ⓧ'
  - trigger: ';oy'
    replace: 'ⓨ'
  - trigger: ';oz'
    replace: 'ⓩ'
  # }}}