matches:
  - trigger: ":a1"
    replace: "ā"
  - trigger: ":a2"
    replace: "á"
  - trigger: ":a3"          
    replace: "ǎ"
  - trigger: ":a4"
    replace: "à"

  - trigger: ":e1"
    replace: "ē"
  - trigger: ":e2"
    replace: "é"
  - trigger: ":e3"          
    replace: "ě"
  - trigger: ":e4"
    replace: "è"

  - trigger: ":i1"
    replace: "ī"
  - trigger: ":i2"
    replace: "í"
  - trigger: ":i3"          
    replace: "ǐ"
  - trigger: ":i4"
    replace: "ì"

  - trigger: ":o1"
    replace: "ō"
  - trigger: ":o2"
    replace: "ó"
  - trigger: ":o3"          
    replace: "ǒ"
  - trigger: ":o4"
    replace: "ò"

  - trigger: ":u1"
    replace: "ū"
  - trigger: ":u2"
    replace: "ú"
  - trigger: ":u3"          
    replace: "ǔ"
  - trigger: ":u4"
    replace: "ù"

  - trigger: ":u:1"
    replace: "ǖ"
  - trigger: ":u:2"
    replace: "ǘ"
  - trigger: ":u:3"          
    replace: "ǚ"
  - trigger: ":u:4"
    replace: "ǜ"
  - trigger: ":u:5"
    replace: "ü"

  - trigger: ":v1"
    replace: "ǖ"
  - trigger: ":v2"
    replace: "ǘ"
  - trigger: ":v3"          
    replace: "ǚ"
  - trigger: ":v4"
    replace: "ǜ"
  - trigger: ":v5"
    replace: "ü"