matches:
  - trigger: "\\--"
    replace: "—"
  - trigger: "\\mdash"
    replace: "—"
  - trigger: "\\emdash"
    replace: "—"
  - trigger: "\\ndash"
    replace: "–"
  - trigger: "\\endash"
    replace: "–"
  - trigger: "\\zwsp"
    replace: "<200b>"
  - trigger: "\\bul"
    replace: "•"
  - trigger: "\\check"
    replace: "✓"
  - trigger: "\\\\sect"
    replace: "§"
  - trigger: "\\rarrow"
    replace: "→"
  - trigger: "\\larrow"
    replace: "←"
  - trigger: "\\uarrow"
    replace: "↑"
  - trigger: "\\darrow"
    replace: "↓"
  - trigger: "\\lrarrow"
    replace: "⟷"